### ISSUE TITLE
Use curl-free version by default on windows?

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#1000]
curl seems to frequently cause issues on windows (including the msys2 component, not just the powershell part). We already have a note about this in the guide wrt certificate errors: https://www.haskell.org/ghcup/guide/#certificate-authority-errors-curl

But users are also reporting non-certificate issues: https://discord.com/channels/280033776820813825/505370075402862594/1206546181405147188

![Screenshot_2024-02-12_18-54-09](https://github.com/haskell/ghcup-hs/assets/1241845/1a02926f-b7ce-4188-9c16-b3f4f799b1c5)

![Screenshot_2024-02-12_18-54-30](https://github.com/haskell/ghcup-hs/assets/1241845/00ad5d7c-3fa2-43db-9022-f587095b2932)

**Comment by runeksvendsen** [comment]
I agree with Cyrus T: if wget seems to work better than curl then use wget by default.

**Comment by Aphexus** [comment]
Tried to install in Windows and it failed in mysys64 about some path error and added disablecurl and it worked.
