### ISSUE TITLE
`stack.yml.lock` and BUILD.md to tell user how to build ghcup from scratch

### ISSUE THREAD

**Issue by evan0greenup** [haskell/ghcup-hs#1008]
It would be nice to provide a `stack.yml.lock` and a `BUILD.md` markdown file to teach users who to build `ghcup-hs` from scratch.

**Comment by hasufell** [comment]
Does `cabal build` or `stack build` not work?

**Comment by evan0greenup** [comment]
@hasufell , Both not working, the reason is due to the version of dependencies.

**Comment by hasufell** [comment]
Yeah, see https://github.com/haskell/ghcup-hs/pull/1007

**Comment by stevenleeS0ht** [comment]
@evan0greenup , @hasufell , It seems that the reason why `stack build` fail is due to the dependency list in `stack.yml` is outdate. I create a pull request. https://github.com/haskell/ghcup-hs/pull/1009

Please have a review and approve it.

**Comment by hasufell** [comment]
This is fixed now.
