### ISSUE TITLE
When build from scratch, the output `ghcup` executable does not have `tui` subcommand

### ISSUE THREAD

**Issue by evan0greenup** [haskell/ghcup-hs#1010]
What additional flag or option should I pass, to make the output executable have `tui` subcommand?

**Comment by hasufell** [comment]
`cabal build -f+tui`

**Comment by hasufell** [comment]
But this flag is already enabled by default: https://github.com/haskell/ghcup-hs/blob/master/cabal.project

So I'm not sure how you are building.

**Comment by evan0greenup** [comment]
@hasufell , I am using `stack build`

**Comment by hasufell** [comment]
That should be fixed by https://github.com/haskell/ghcup-hs/pull/1007 soon
