### ISSUE TITLE
my `tmp` dir in `.ghcup` grew to more than 10 GB

### ISSUE THREAD

**Issue by andrewufrank** [haskell/ghcup-hs#1011]
I have the impression, that the `tmp` directory can be deleted - at least most of the time. Some information would be appreciated but perhaps it is possible to automatically delete the files in the `tmp` directory automatically after they are not used anymore. 

I use GHCup 0.1.20.0  with debian 12.

Thank you very much for a higly appreciated tool!

**Comment by andrewufrank** [comment]
I must have had some troubles (or an issue with vs code trying to install something repeatedly...) and the tmp became large. thank you for the hint with `ghcup gc`. I nearly always use `ghcup tui` which is extremely useful, but does not advertice `gc`. I learned something - thank you!

**Comment by hasufell** [comment]
Hmm, this is the second time someone reporting issues with vscode and tmp size growing. 

@tomjaguarpaw @fendor

**Comment by andrewufrank** [comment]
I see regularly a message in vscode `need to download hls 23.... . continue`. it seems to come from the extension `Haskell` - then it says `Installing project specific toolchain: hls-2.3.0.0, GHC-9.6.2, cabal-3.10.2.1, stack-2.15.1`. These messages are repeated when I log in into VS code to edit haskell code. I assume that something does not complete and then perhaps the `tmp` dir is not cleaned. Does that help?

**Comment by andrewufrank** [comment]
I see that the installation is continuing and using both a lot of cpu and disk space. 
I see now:
````
frank@bhutan:~/.ghcup/tmp$ dir -lsa
total 16
4 drwxr-xr-x  4 frank frank 4096 24. Feb 17:57 .
4 drwxr-xr-x 10 frank frank 4096 23. Feb 18:07 ..
4 drwxr-xr-x  2 frank frank 4096 24. Feb 17:46 ghcup-cabal-3.10.2.1_hls-2.2.0.0_stack-2.15.1
4 drwxr-xr-x  2 frank frank 4096 24. Feb 17:57 ghcup-ghc-9.6.2_cabal-3.10.2.1_hls-2.3.0.0_stack-2.15.1
````
which is really unpleasant (and I have no need for `stack` to install, I use `cabal`). How to avoid this?

**Comment by hasufell** [comment]
The directories you're looking at only contain symbolic links. I'm not sure what's unpleasant about that.

**Comment by andrewufrank** [comment]
True. The unpleasant part was the cpu load, which made my (old) computer unresponsive. 
What I really dislike is the repeated effort to carry out an installation for which I have no use and do not understand where and why it was started. - I assume that there was a connection to your observation that this was the second time somebody mentioned tmp growing with connection to vscode. 
The undesired installation of stack is not an issue which warrants much attention. Thank you for your efforts - `ghcup` is really a wonderful tool to install ghc!

**Comment by tomjaguarpaw** [comment]
This happened to me and it was because HLS chose to use stack over cabal, and stack decided it wanted to install a specific version of GHC. I wrote about it at https://discourse.haskell.org/t/why-is-hls-asking-ghcup-to-install-ghc/8734

There are two solutions and it's probably best to enact them both:

1. `stack config set install-ghc false --global`, to tell stack never to try to install ghc
2. Add a `hie.yaml` file and tell HLS to use the `cabal` cradle, because it will try to use the stack one by default. It should contain these two lines:

       cradle:
           cabal:

**Comment by hasufell** [comment]
@tomjaguarpaw but why did that lead to a cluttered tmp dir?

**Comment by tomjaguarpaw** [comment]
Because of this behaviour:

> Often I don’t have enough free space, so it just dies. I’ve ended up with `.ghcup/tmp` containing 8 GB of temporary files from aborted installs!

When `ghcup` terminates because there wasn't enough disk space it doesn't clean out `tmp`. As I recall it *does* print out an advice message that you should manually clean out `tmp` but because it was an unattended install, no one ever sees that message.

**Comment by hasufell** [comment]
We catch exceptions and clean up, but we use `Control.Exception.Safe` which ignores async exceptions (which includes ctrl+c and out of disk space, I guess).
