### ISSUE TITLE
`ghcup tui` fails with STM error in Windows Terminal 1.19

### ISSUE THREAD

**Issue by hreinhardt** [haskell/ghcup-hs#1013]
Running `ghcup tui` in Windows Terminal 1.19 leads to an immediate crash with the error message:

```
ghcup: thread blocked indefinitely in an STM transaction
```

It works fine in Windows Terminal 1.18

My GHCup version is 0.1.20.0

**Comment by hasufell** [comment]
This should probably be reported to brick/vty maintainers.

**Comment by hreinhardt** [comment]
Thanks for the pointer. It might be the same problem as this: https://github.com/jtdaugherty/brick/issues/502

**Comment by hasufell** [comment]
Reopening, because we need to bump brick/vty once there is a fix and release a new ghcup version. I hope I can get it in for the next release.

**Comment by MonsieurOrnix** [comment]
Hi ! Same error message for me when running `ghcup tui` in Windows Terminal 1.19, _but it works perfectly well in VSCode terminal_.

**Comment by hasufell** [comment]
Yes, it's already fixed, but not released yet.
