### ISSUE TITLE
GHCI missing newline character after pressing enter

### ISSUE THREAD

**Issue by B-Teague** [haskell/ghcup-hs#1015]
I was testing the GHCI repl on Windows WSL2 on Debian, and noticed it was not including a newline character when pressing enter for commands:

```bash
❯ ghci
GHCi, version 9.8.1: https://www.haskell.org/ghc/  :? for help
ghci> 1 + 12
ghci> double x = x + xghci> double 24
ghci>
```

**Comment by hasufell** [comment]
I don't think this is an issue with GHCup. Please report it to the GHC issue tracker: https://gitlab.haskell.org/ghc/ghc/-/issues
