### ISSUE TITLE
feature request: command to remove old versions

### ISSUE THREAD

**Issue by peterbecich** [haskell/ghcup-hs#1019]
Old versions of GHC, HLS, Cabal and Stack are kept by ghcup, a good idea to allow the user to revert to an older version.

I.m.o. a command to remove tool versions lower than what is currently `set` by the user would be useful.

This would save the effort of manually `rm`ing each old version.

Perhaps `ghcup clean`

Thanks

**Comment by hasufell** [comment]
There's already `ghcup gc --old-ghc`. But that relies on what is marked `Old` in the ghcup metadata, so might not remove everything.

**Comment by hasufell** [comment]
See https://github.com/haskell/ghcup-hs/pull/1020

This removes all "non-set versions" (of all tools). Anything more specific seems overkill to me.

**Comment by peterbecich** [comment]
Fantastic, looks good to me, thank you

**Comment by blueglyph** [comment]
For future references, it's actually `ghcup gc --ghc-old`.

I probably missed something with the comment about #1020, since there's no comments over there, but I found that `ghcup gc --unset` removed all non-set versions, so I suppose that's the other way to proceed.
