### ISSUE TITLE
Can't open issues upstream

### ISSUE THREAD

**Issue by B-Teague** [haskell/ghcup-hs#1022]
I apologize for opening an issue here again, but I don't know what else to do.

I was asked to open an issue upstream https://gitlab.haskell.org/ghc/ghc/-/issues for a bug I believe I found with the GHCI repl.

However, after registering a new account, I cannot create an issue because of the following error:
"Your account is pending approval from your GitLab administrator and hence blocked. Please contact your GitLab administrator if you think this is an error. "

I cannot contact a GitLab administrator for the Haskell website to fix this.

Any help would be greatly appreciated.

**Comment by chreekat** [comment]
Hi @B-Teague , I will approve your account. If anyone asks in the future, you can send a message to #ghc on IRC, or [GHC on Matrix](https://matrix.to/#/!pAORzwKXYKXnnMpVxT:matrix.org?via=chreekat.net&via=matrix.org&via=tryp.io), or join the ghc-devs mailing list at https://mail.haskell.org/cgi-bin/mailman/listinfo/ghc-devs and send a message.

**Comment by hasufell** [comment]
@chreekat

**Comment by B-Teague** [comment]
Thank you!
