### ISSUE TITLE
Feature request, add build option to disable auto-update for `ghcup` itself

### ISSUE THREAD

**Issue by evan0greenup** [haskell/ghcup-hs#1028]
For the system which install `ghcup` as system package, the version of `ghcup` itself is managed by system package manager. 

So, it would be nice not to let `ghcup` download new version of `ghcup` during compile time.

**Comment by hasufell** [comment]
> So, it would be nice not to let ghcup download new version of ghcup during compile time.

I don't understand what this means. "During compile time"? GHCup only performs updates when the user duns `ghcup upgrade` and even then **does not do an in-place update** by default in order to not conflict with package managers. It will place the new binary in the ghcup bindir.

**Comment by evan0greenup** [comment]
@hasufell , I mean when add certain flag or environment variable for `stack build`.

Then the produced `ghcup` executable will not download new version `ghcup` when run `ghcup upgrade`.

**Comment by hasufell** [comment]
No, I won't support that feature. This previously broke VSCode haskell extension, so it was reverted: https://github.com/haskell/vscode-haskell/issues/601

**Comment by evan0greenup** [comment]
@hasufell , 

No, I mean when enable the flag I proposed,  `ghcup upgrade` is still existed and update metadata, there is no error on it. But It will no longer download new version of `ghcup`.

**Comment by hasufell** [comment]
I don't really want people to ship crippled versions of ghcup. There's no guarantee that distributors update ghcup in time or at all.

End users should always have the option to use `ghcup upgrade` to trigger an immediate update.

There's no reason to remove that feature.
