### ISSUE TITLE
Windows unsupported processor architecture: ARM64

### ISSUE THREAD

**Issue by alt-romes** [haskell/ghcup-hs#1034]
When running an Windows in a virtual arm machine, hosted on a mac with an M2 chip, I ran into this bug when installing GHC via GHCup:

```
Unsupported processor architecture: ARM64. Supported architectures: AMD64, x86.
```

Though I now realise upstream may not really support aarch64 windows

**Comment by hasufell** [comment]
Yes, it's unsupported. Not a bug.

Duplicate of https://github.com/haskell/ghcup-hs/issues/973
