### ISSUE TITLE
Can't install GHCup on Windows due to MSys2 error

### ISSUE THREAD

**Issue by jawadcode** [haskell/ghcup-hs#1035]
I attempted to re-install GHCup on Windows after nuking, deleting all of the ghcup, cabal and stack directories as well as deleting environment variables and it failed at some point in the MSys2 installation process.

I don't have much information other than the output before the powershell command exits:
```
Exception: Exec: Error executing command C:\\ghcup\msys64\usr\bin\bash with arguments '-lc exit'
```
I imagine this is the only line of output because MSys2 likes to randomly clear the screen.

**Comment by hasufell** [comment]
Try to follow the manual installation steps outlined here:

* https://www.haskell.org/ghcup/install/#windows_1

**Comment by hasufell** [comment]
I'll close this ticket in a week, unless there's further information.

**Comment by jawadcode** [comment]
> I'll close this ticket in a week, unless there's further information. 

Sorry about abandoning this issue, I decided to resolve the situation by installing msys2 and ghcup itself through [Scoop](https://scoop.sh/).
