### ISSUE TITLE
Ubuntu: Installation suggest non-existing package

### ISSUE THREAD

**Issue by jasagredo** [haskell/ghcup-hs#1038]
It is not particularly problematic, but the installation on a fresh ubuntu machine suggests `libffi8ubuntu1` and that package seems to not exist anymore ([link](https://packages.ubuntu.com/search?suite=kinetic&section=all&arch=any&keywords=libffi8ubuntu1&searchon=names)). `apt` is able to manage anyways:

```
javier@EVA-01:~$ curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

Welcome to Haskell!
...
System requirements
  Please ensure the following distro packages are installed before continuing (you can exit ghcup and return at any time): build-essential curl libffi-dev libffi8ubuntu1 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5
Press ENTER to proceed or ctrl-c to abort.
Installation may take a while.

...

javier@EVA-01:~$ sudo apt install build-essential curl libffi-dev libffi8ubuntu1 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libffi8' instead of 'libffi8ubuntu1'
libffi8 is already the newest version (3.4.2-4).
libffi8 set to manually installed.
...
```

**Comment by hasufell** [comment]
Please state the exact distro version you're running when opening distro related tickets. I'm assuming it's jammy 22.04 LTS.


https://github.com/haskell/ghcup-metadata/pull/198

**Comment by jasagredo** [comment]
You are right, I should have said it. It is indeed the one that comes with WSL, jammy 22.04 LTS. 

Thanks for the quick fix
