### ISSUE TITLE
Suggest or install pkg-config

### ISSUE THREAD

**Issue by Bodigrim** [haskell/ghcup-hs#1039]
Haskell package ecosystem works better and is more secure when `pkg-config` executable is available. Could `ghcup` 

* suggest to install `pkg-config` alongside other system packages on Unix,
* install `pkg-config` in MSYS environment on Windows?

Or am I barking mad?

**Comment by hasufell** [comment]
> suggest to install pkg-config alongside other system packages on Unix,

We could. It's here https://github.com/haskell/ghcup-metadata/blob/1d55bd79dc338dfd3843d26b27dc9340b4b7f6c5/ghcup-0.0.8.yaml#L6

> install pkg-config in MSYS environment on Windows?

I think we already do?

https://github.com/haskell/ghcup-hs/blob/eebbc9908bafbc3994e5d1572ef9c4f77f35ffdb/scripts/bootstrap/bootstrap-haskell.ps1#L536

**Comment by Bodigrim** [comment]
> I think we already do?

Nice! Is Stack able to use this MSYS environment or does it insist on installing its own?

**Comment by hasufell** [comment]
> > I think we already do?
> 
> Nice! Is Stack able to use this MSYS environment or does it insist on installing its own?

Through a combination of these config options:

- skip-msys
- extra-path
- extra-include-dirs
- extra-lib-dirs

It's a bit manual.

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-hs/issues/1040

**Comment by hasufell** [comment]
https://www.haskell.org/ghcup/guide/#using-ghcups-msys2-installation
