### ISSUE TITLE
ghcup install cabal from gitlab under aarch64-darwin giving decoding error LzmaRetFormatError

### ISSUE THREAD

**Issue by soulomoon** [haskell/ghcup-hs#1049]
❯ ghcup install cabal -u 'https://gitlab.haskell.org/haskell/cabal/-/jobs/1848815/artifacts/file/out/cabal-install-3.11.0.0-aarch64-darwin.tar.xz' 3.12.0.0-prerelease -v
[ Debug ] Identified Platform as: Darwin
[ Debug ] last access was 250.508058s ago, cache interval is 300s
[ Debug ] Decoding yaml at: /Users/ares/.ghcup/cache/ghcup-0.0.8.yaml
[ Debug ] Requested to install cabal version 3.12.0.0-prerelease
[ Info  ] downloading: https://gitlab.haskell.org/haskell/cabal/-/jobs/1848815/artifacts/file/out/cabal-install-3.11.0.0-aarch64-darwin.tar.xz as file /Users/ares/.ghcup/tmp/ghcup-dd2f39cf544bde11/cabal-install-3.11.0.0-aarch64-darwin.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27575  100 27575    0     0  19279      0  0:00:01  0:00:01 --:--:-- 19269
[ Info  ] Unpacking: cabal-install-3.11.0.0-aarch64-darwin.tar.xz to /Users/ares/.ghcup/tmp/ghcup-3509417a913f686a
ghcup: Codec.Compression.Lzma.decompressWith: decoding error LzmaRetFormatError
CallStack (from HasCallStack):
  error, called at src/Codec/Compression/Lzma.hs:95:13 in lzm-sttc-5.2.5.5-b1505c61:Codec.Compression.Lzma

**Comment by soulomoon** [comment]
Work around, manually zip in local 
`ghcup install cabal -u 'file:///Users/ares/Downloads/cabal-install-3.11.0.0-aarch64-darwin/cabal.zip' 3.12.0.0-prerelease
`

**Comment by hasufell** [comment]
Your url is invalid. This is a user error. The correct url is https://gitlab.haskell.org/haskell/cabal/-/jobs/1848815/artifacts/raw/out/cabal-install-3.11.0.0-aarch64-darwin.tar.xz

**Comment by soulomoon** [comment]
thanks for correcting
