### ISSUE TITLE
Internal downloader throws `ContentLengthError`

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#1055]
```
$ ghcup --downloader=internal tui
[ Info  ] downloading: https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-0.0.8.yaml as file /home/hasufell/.ghcup/cache/ghcup-0.0.8.yaml
[============================================================================================================================================] 141%
ghcup: ContentLengthError Nothing (Just 98256) 69674
```

**Comment by dfordivam** [comment]
The issue here is that the file is being sent as gzipped (content-encoding gzip), and the size comparison happens with the gzipped sized (specified in content-length), and the uncompressed size.

This check may be removed as the `receiveResponse` does uncompress internally (as described in haddocks of `receiveResponseRaw`)

> receiveResponseRaw :: [Connection](https://hackage.haskell.org/package/http-io-streams-0.1.7.0/docs/Network-Http-Client.html#t:Connection) -> ([Response](https://hackage.haskell.org/package/http-io-streams-0.1.7.0/docs/Network-Http-Client.html#t:Response) -> [InputStream](https://hackage.haskell.org/package/io-streams-1.5.2.2/docs/System-IO-Streams-Internal.html#t:InputStream) [ByteString](https://hackage.haskell.org/package/bytestring-0.11.5.2/docs/Data-ByteString.html#t:ByteString) -> [IO](https://hackage.haskell.org/package/base-4.18.1.0/docs/System-IO.html#t:IO) β) -> [IO](https://hackage.haskell.org/package/base-4.18.1.0/docs/System-IO.html#t:IO) β
> 
> This is a specialized variant of [receiveResponse](https://hackage.haskell.org/package/http-io-streams-0.1.7.0/docs/Network-Http-Client.html#v:receiveResponse) that explicitly does not handle the content encoding of the response body stream (it will not decompress anything). Unless you really want the raw gzipped content coming down from the server, use receiveResponse.

**Comment by hasufell** [comment]
Nice catch. Can you provide a PR?
