### ISSUE TITLE
`--platform` option does not accept ARM platforms?

### ISSUE THREAD

**Issue by andreasabel** [haskell/ghcup-hs#1057]
Seems like the parser for the `--platform` option only supports `i386` and `x86_64`, not `arm` architectures:
https://github.com/haskell/ghcup-hs/blob/ea964ee077a3f235f3d31aa86e6a50d2c7359603/lib-opt/GHCup/OptParse/Common.hs#L179-L185

I was trying something like `ghcup list --platform aarch64-darwin` to find out which Haskell tools are supported on this architecture.
This was triggered by the error `Unable to find a download for Cabal version '3.2.0.0' on detected platform aarch64-darwin` at https://github.com/haskell-actions/setup/actions/runs/8763086208/job/24560761677#step:3:97

```
$ ghcup list -p aarch64-darwin
option -p: 1:1:
  |
1 | aarch64-darwin
  | ^^^^^^
unexpected "aarch6"
expecting "i386" or "x86_64"

$ ghcup list -p aarch64-apple-darwin
option -p: 1:1:
  |
1 | aarch64-apple-darwin
  | ^^^^^^
unexpected "aarch6"
expecting "i386" or "x86_64"
```

**Comment by hasufell** [comment]
You're right. That should be done better with pretty print instance and utilizing bounded class or something

However, there's another way to do it, via config: https://www.haskell.org/ghcup/guide/#overriding-distro-detection

E.g.: `ghcup config set platform-override '{ "arch": "A_ARM64", "platform": { "tag": "Darwin" }, "version": "14.0" }'`

But it's permanent unless you delete it again from the config. And I realized there's no easy way to remove a config key via `ghcup config`.

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-hs/pull/1059
