### ISSUE TITLE
GHCup tries to modify non-existent `~/.zshrc`

### ISSUE THREAD

**Issue by jasagredo** [haskell/ghcup-hs#1063]
On Ubuntu 23.10, when installing ghcup, I am propmted with the following message:
```
❯ curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
...
Detected zsh shell on your system...
Do you want ghcup to automatically add the required PATH variable to "/home/javier/.zshrc"?

[P] Yes, prepend  [A] Yes, append  [N] No  [?] Help (default is "P").
```

However, my `.zshrc` is not there, but instead in `$ZDOTDIR/.zshrc` (which in my case is `~/.config/zsh/.zshrc`)

Perhaps GHCup could check `${ZDOTDIR:-$HOME}/.zshrc` instead, or at least if the file is not there, tell the user.

**Comment by hasufell** [comment]
These `.profile` shenanigans are a disaster and I wish I never started with it.

Feel free to provide a PR.

**Comment by jasagredo** [comment]
It seems the error was on my side. I was debugging the error to provide a PR, and found out that the script didn't inherit the `~/.zshenv` variables. Turns out I missed the `export` keyword there, which set the var for the shell, but not for scripts. Changing my `~/.zshenv` makes it work already.
