### ISSUE TITLE
Feature request: `ghcup msys2 set <env>` to switch MSYS2 environments seen by `cabal`

### ISSUE THREAD

**Issue by jasagredo** [haskell/ghcup-hs#1088]
Today I was compiling a `cabal` locally and I downgraded to GHC 8.10.7 to check some stuff. Turns out that GHC 8.10.7 is based on `mingw64` and therefore is incompatible with `ucrt64` environment.

To solve this I had to modify my `cabal` config to point to point to `<msys2-dir>\mingw64\...` instead of what I had before `<msys2-dir>\ucrt64\...` as described here: https://cabal.readthedocs.io/en/stable/how-to-run-in-windows.html.

Would it be reasonable that GHCup is able to perform this switch with a command? it knows the location of the msys2 installation and knows the current environment set in the cabal config file.

FTR, using GHC 9.x requires an UCRT-based environment at least from what I have observed. Should also GHCup default to UCRT64 from the bootstrap?

**Comment by jasagredo** [comment]
Actually, seems that I was able to compile things in GHC 9.6.5 while still pointing to `mingw64` environment on my cabal config, not sure what is going on. Let me try to clarify this in the coming days.

**Comment by jasagredo** [comment]
I assume all symbols in `msvcrt` exist in `ucrt` but not the other way round, and it "just works ™️". I am clarifying this in the documentation https://github.com/haskell/cabal/pull/10154

**Comment by hasufell** [comment]
Conceptually, ghcup is not supposed to be an interface for changing cabal configuration. 

That's what `cabal user-config` is for.

**Comment by jasagredo** [comment]
I spent some more time tinkering with my system and actually this function is good enough for me, just leaving it here for closing the issue and in case someone in the future finds it useful:

```
cabal-msys2-env () {
  sed -i "s/\(ucrt\|mingw\|clang\)/$1/g" $(cygpath -u "$(cabal --help | tail -n1 | sed 's_\r__g' | tr -d ' ')")
}
```
