### ISSUE TITLE
Will there be binaries for aarch64 alpine?

### ISSUE THREAD

**Issue by mpickering** [haskell/ghcup-hs#1096]
It seems there aren't currently ghcup binaries for aarch64 alpine. Are there plans to provide binaries for this platform in future?

(I don't have a personal use for these binaries but I have added test jobs to `ghcup-ci` in anticipation one day ghcup will support installing on this platform)

**Comment by hasufell** [comment]
Yeah, see https://github.com/haskell/ghcup-hs/issues/1012

GHCup can't be built with 9.8.2 yet, so that needs to be done first.

**Comment by mpickering** [comment]
Thanks, I will close in favour of #1012
