### ISSUE TITLE
[regression] TUI keybinding ignored

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#1099]
Since 0.1.30.0 it seems TUI keybindings via the config file don't work anymore: https://github.com/haskell/ghcup-hs/issues/1098#issuecomment-2216232215

@lsmor @dfordivam

**Comment by dfordivam** [comment]
Now I recall why it can't be configurable in the current design. When the input field is selected, the editing of the input fields is done by simply typing, and only the up/down arrow support moving the focus. Therefore to make it configurable a re-design of input fields would be necessary, like first press enter to open the edit dialog, then type in it.

This could be done via the overlay design I am currently implementing, though that would mean that direct editing of text fields would no longer be possible.

**Comment by hasufell** [comment]
I'm ok with keybindings only applying to the main widget and not the popups.

This is a regression, so I want to fix it quickly and make a point release.

**Comment by lsmor** [comment]
In the comments of the issue it seems like it is solved. Currently we don't have keybindings for Tutorial not context menu. Also, part of the `KeyBinding` infrastructure in `ghcup` seems to replicate/duplicate that in [`brick`](https://hackage.haskell.org/package/brick-2.4/docs/Brick-Keybindings.html). Probably we should move it to brick.
