### ISSUE TITLE
Allow to set BOOTSTRAP version for stack and HLS

### ISSUE THREAD

**Issue by juergenpf** [haskell/ghcup-hs#1103]
The script allows to set BOOTSTRAP environment variables for ghc and cabal, but not for stack and HLS. 
Please add that for consistency, so one can control completely which versions to be installed of ANY of the tools in an initial install.

**Comment by hasufell** [comment]
Sounds reasonable. PRs welcome

**Comment by juergenpf** [comment]
Thx. I‘ve submitted a PR.
