### ISSUE TITLE
Error: key "ghc" not found

### ISSUE THREAD

**Issue by brandonchinn178** [haskell/ghcup-hs#1110]
Any ghcup command I run, including `ghcup upgrade` or `ghcup tui`, shows the following output:
```
[ Info  ] downloading: https://ghc.gitlab.haskell.org/ghcup-metadata/ghcup-nightlies-0.0.7.yaml as file /Users/bchinn/.ghcup/cache/ghcup-nightlies-0.0.7.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  606k  100  606k    0     0   964k      0 --:--:-- --:--:-- --:--:--  963k
[ Error ] [GHCup-00160] JSON decoding failed with: Aeson exception:
[ ...   ] Error in $: key "ghc" not found
[ ...   ] Consider removing /Users/bchinn/.ghcup/cache/ghcup-nightlies-0.0.7.yaml manually.
```

Removing the specified file doesn't help. Rerunning `curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh` doesn't help either. Presumably the issue is the nightlies channel here, but 1) I'm not sure why it just started failing, and 2) I don't see any `ghcup config` command to reset the URL.

Manually editing `~/.ghcup/config.yaml` to `https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-0.0.8.yaml` seems to work, but there should be a more ergonomic solution.

**Comment by hasufell** [comment]
https://www.haskell.org/ghcup/guide/#metadata

```yaml
url-source:
  - GHCupURL
```

```sh
ghcup config set url-source GHCupURL
```

----

And indeed, I don't maintain the nightlies and don't give support for them.

You'll have to raise an issue for that at the GHC issue tracker.

**Comment by hasufell** [comment]
@dfordivam I guess we could overhaul the `ghcup config --help` text to include such basic operations.

https://github.com/haskell/ghcup-hs/blob/6c69229af4823d35c9accd627b1e47be47334326/lib-opt/GHCup/OptParse/Config.hs#L101-L110

The parser for `url-source` is now quite lenient and accepts a list even:

https://github.com/haskell/ghcup-hs/blob/6c69229af4823d35c9accd627b1e47be47334326/lib/GHCup/Types/JSON.hs#L310-L386

**Comment by brandonchinn178** [comment]
Before I raise an issue in the GHC issue tracker, can we double check that the fix is on their side? Presumably there's a data type in ghcup that's parsing a `ghc` field; I would expect the fix to be "fix ghcup to parse the nightly metadata correctly", not "make the metadata work with ghcup"

**Comment by hasufell** [comment]
> I would expect the fix to be "fix ghcup to parse the nightly metadata correctly", not "make the metadata work with ghcup"

"make the metadata work with ghcup" is exactly what I expect from third party metadata files :)

**Comment by mpickering** [comment]
Thanks for reporting @brandonchinn178, I have fixed the issue on the GHC side (manually for existing metadata and fixed the generation script). 

On the ghcup side, it seems that the actual parsing error is swallowed (#1113) so I put up a patch which prints that out in verbose mode.

**Comment by mpickering** [comment]
Fix is merged on the GHC side now. I think think this issue can be closed.
