### ISSUE TITLE
`cabal-hoogle` gets reported as a stray `cabal` with version `hoogle`

### ISSUE THREAD

**Issue by aikrahguzar** [haskell/ghcup-hs#1111]
I have a tool called cabal-hoogle installed. its helps with managing local hoogle indices for cabal-projects. However ghcup picks it up and reports it as a `cabal` with version `hoogle` as can be see below
![cabal-hoogle](https://github.com/user-attachments/assets/683760aa-67aa-4822-a021-607ff2573c52)

I think it would be better to consider versions to start with a number.

Thanks for ghcup!

**Comment by hasufell** [comment]
> I think it would be better to consider versions to start with a number.

This would be a breaking change and it's actually a feature to allow non-numeric versions and is used when e.g. installing custom ghc bindists.

The proper fix is https://github.com/haskell/ghcup-hs/issues/375

However, all this is only an issue when using XDG dirs.

I've been pondering to drop support for XDG.

**Comment by aikrahguzar** [comment]
> > I think it would be better to consider versions to start with a number.
> 
> This would be a breaking change and it's actually a feature to allow non-numeric versions and is used when e.g. installing custom ghc bindists.

Are there versions that start with a non-numeric identifier? I have mostly seen version with a numeric prefix and a non-numeric suffix.
 
> The proper fix is #375

I will close this in favor of #375 then.

> However, all this is only an issue when using XDG dirs.
> 
> I've been pondering to drop support for XDG.

Please don't. I think it is a good standard.
