### ISSUE TITLE
Feature request: Make `ghcup list --hide-old` (`-o`) the default

### ISSUE THREAD

**Issue by mpilgrem** [haskell/ghcup-hs#1115]
For `ghcup tui`, not showing old versions is the default and key 'a' toggles between the default and showing old versions also.

Currently `ghcup list` shows old versions also, and `--hide-old` (`-o`, for short) is passed to filter out all old versions (not just GHC old versions, as stated by in-app help).

As `ghcup list` grows in length, I suggest that `--hide-old` is the sensible default, with a flag for `--no-hide-old`.

**Comment by hasufell** [comment]
That would be a breaking change. People are using `ghcup list` in scripts (github runners even used to). So any changes to that could cause large breakage. Sure, we could have a different default when `--raw-format` is passed, but that would complicate the interface (and you can still sed/grep even without it).

**Comment by mpilgrem** [comment]
It is a minor thing now `ghcup tui` supports Windows. In my case, 'muscle memory' means that I still command `ghcup list` in error (as what I need to avoid the 'noise' of old versions is `ghcup list -o` or `ghcup tui`). 

Is there a reason why the output of `ghcup list` does not reveal the `Old` tag - it does not distinguish 'Old' from 'other non-Latest'?

**Comment by hasufell** [comment]
> Is there a reason why the output of ghcup list does not reveal the Old tag - it does not distinguish 'Old' from 'other non-Latest'?

Since it's kind of an arbitrary selection, I'm not sure having that information permanently visible is useful.

----

Regarding the output length: we coulq drop into the pager when the output exceeds terminal height (or is used as part of a pipe... it's possible to detect that programmatically... git does that too).

**Comment by hasufell** [comment]
The other discussion about pager is here: https://github.com/haskell/ghcup-hs/issues/1118
