### ISSUE TITLE
gpg --verify fails on SHA256SUMS from downloads.haskell.org in 0.1.30.0

### ISSUE THREAD

**Issue by rhinoduck** [haskell/ghcup-hs#1121]
Source of the files: https://downloads.haskell.org/~ghcup/0.1.30.0/

```
$ gpg --verify SHA256SUMS.sig SHA256SUMS
gpg: Signature faite le So 17. srpna 2024, 11:59:20 CEST
gpg:                avec la clef RSA ECA44F5A172EDAD947F39E3D4275CDA6A29BED43
gpg:                issuer "hasufell@posteo.de"
gpg: MAUVAISE signature de « Julian Ospald <maerwald@hasufell.de> » [inconnu]
```

From what I can see, there seem to be additional `aarch64-linux-static-ghcup-0.1.30.0` files with a newer modification timestamp than the other files; the SHA256SUMS files also have this newer timestamp. The SHA256SUMS file does not contain cheksums for the new `static` builds. 

Maybe something that should have been updated was not, or something that should not have been updated was? Either way, the integrity check of the SHA256SUMS file is currently failing for me.

**Comment by hasufell** [comment]
It's the CDN cache. The files are all correct. In such cases you can run:

```sh
curl -X PURGE https://downloads.haskell.org/~ghcup/0.1.30.0/SHA256SUMS
curl -X PURGE https://downloads.haskell.org/~ghcup/0.1.30.0/SHA256SUMS.sig
```

**Comment by hasufell** [comment]
> It's the CDN cache. The files are all correct. In such cases you can run:
> 
> ```shell
> curl -X PURGE https://downloads.haskell.org/~ghcup/0.1.30.0/SHA256SUMS
> curl -X PURGE https://downloads.haskell.org/~ghcup/0.1.30.0/SHA256SUMS.sig
> ```

To add: don't run this in scripts or dockerfiles. This is a one-time issue.

**Comment by rhinoduck** [comment]
Unfortunate timing on my part, I see. Caching did not occur to me. Thank you for the tip.
