### ISSUE TITLE
Is it typo? 'c+Ctrl'

### ISSUE THREAD

**Issue by dontdieych** [haskell/ghcup-hs#1130]
![Screenshot_20240920_020749](https://github.com/user-attachments/assets/6c4a3f2c-ec6e-4e64-aee8-14c4c2ddad9a)

Anyway thanks for developing this nice tool. Cheers.

**Comment by hasufell** [comment]
Why would it be a typo?

**Comment by hasufell** [comment]
Ah, right... yop mean `ctrl+c`?

**Comment by dfordivam** [comment]
This gets "fixed" (or rather hardcoded shortcuts replaced with user specified key) in https://github.com/haskell/ghcup-hs/pull/1102

**Comment by dontdieych** [comment]
> This gets "fixed" (or rather hardcoded shortcuts replaced with user specified key) in #1102

Yup, Alright.
