### ISSUE TITLE
curl: (35) error:0A000126:SSL routines::unexpected eof while reading

### ISSUE THREAD

**Issue by okanakyuz** [haskell/ghcup-hs#1135]
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

returns curl: (35) error:0A000126:SSL routines::unexpected eof while reading

**Comment by dfordivam** [comment]
@okanakyuz This appears to be a temp server issue, should be resolved soon. Please check a few minutes later

**Comment by zoezhangmattr** [comment]
i also have similar issue, 
curl: (56) Recv failure: Connection reset by peer
sh: line 569: syntax error near unexpected token `newline'
sh: line 569: `                                 case '

**Comment by zoezhangmattr** [comment]
is the server stable now, i still have same error

**Comment by dfordivam** [comment]
Seems to be working right now.

```
$ curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | wc
    955    3028   27921

$ wc scripts/bootstrap/bootstrap-haskell
  955  3028 27921 scripts/bootstrap/bootstrap-haskell
```

**Comment by dfordivam** [comment]
Right, there is some problem, I could reproduce it at least once

 curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | wc
curl: (56) Recv failure: Connection reset by peer
    568    1701   16366

**Comment by mpickering** [comment]
Still seems to be failing intermittently. (All 100 jobs here are calling that command, some pass, some fail - https://gitlab.haskell.org/ghc/ghcup-ci/-/pipelines/101598)

**Comment by gbaz** [comment]
I believe this was due to our host (equinix metal) undergoing infrastucture maintenance: https://status.equinix.com/history

**Comment by dfordivam** [comment]
This seems to be resolved now
