### ISSUE TITLE
Error by installing ghc

### ISSUE THREAD

**Issue by BartTheBartender** [haskell/ghcup-hs#1147]
I have downloaded ghcup from brew and proceeded to install ghc via $ ghcup install ghc. I got the error:

ghcup install ghc
ghcup: ParseErrorBundle {bundleErrors = TrivialError 9 (Just EndOfInput) (fromList []) :| [], bundlePosState = PosState {pstateInput = "ghc-9.4.8", pstateOffset = 0, pstateSourcePos = SourcePos {sourceName = "ghcLinkVersion", sourceLine = Pos 1, sourceColumn = Pos 1}, pstateTabWidth = Pos 8, pstateLinePrefix = ""}}

**Comment by hasufell** [comment]
Is the env var `GHCUP_USE_XDG_DIRS` set?

**Comment by BartTheBartender** [comment]
Thank you for the answer! I have set the variable to „true”, the error still persists.

**Comment by hasufell** [comment]
I did not suggest to set it to true. Please unset the env var.

**Comment by hasufell** [comment]
feel free to reopen with more information
