### ISSUE TITLE
default GHC on fresh GHCup installation is 9.4?

### ISSUE THREAD

**Issue by peterbecich** [haskell/ghcup-hs#1166]
I've just re-installed GHCup.

`ghcup nuke` followed by
```
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
```
and following the wizard.

It is installing GHC 9.4.  Can this be updated to 9.6 or later?  9.6 is the recommended version, right?

Thanks

**Comment by peterbecich** [comment]
Nevermind, I see 9.4 is recommended:
```
✔✔ ghc   9.4.8      recommended,base-4.17.2.1 hls-powered           
```

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-metadata/issues/220
