### ISSUE TITLE
feat(docs): Installation guide doesn't mention requirements for WSL 

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/ghcup-hs#1183]
### Problem

The [guide](https://www.haskell.org/ghcup/install/) mentions the required packages for various Linuxes, including Ubuntu, which powers WSL. However, in my experience, Windows/WSL is used by many newcomers who may not be aware of the connection.

### Proposal

Add a WSL subsection under the Windows section saying something to the effect of "follow instructions for ~~Ubuntu~~ your Linux distro".

**Comment by ShrykeWindgrace** [comment]
You can run different distros in WSL, inluding, and not limited to, Ubuntu, Debian, Alpine, Fedora, and Arch. I guess the best course of action is to add a line "WSL: follow the instructions for the distro you picked".

**Comment by Dmitry2112** [comment]
I suggest adding a [link](https://www.haskell.org/ghcup/install/) to the instructions page for a specific distribution to the [get started page](https://www.haskell.org/get-started/) and adding information that additional packages may be required for ghc to work correctly.

**Comment by hasufell** [comment]
Feel free to open a PR.

**Comment by Dmitry2112** [comment]
I opened a [PR](https://github.com/haskell/ghcup-hs/pull/1184)

**Comment by hasufell** [comment]
done

**Comment by ulysses4ever** [comment]
Thanks!
