### ISSUE TITLE
Create ghc.exe shim on Windows

### ISSUE THREAD

**Issue by fleimgruber** [haskell/ghcup-hs#1194]
As a user, if I install GHC via
```
ghcup install ghc 9.10
```
and set it to the default GHC via
```
ghcup set ghc 9.10
```
there is no `ghc.exe` (or similar shim).

What's wrong with the expectation that ghcup provides a way to have `ghc` on the CLI?

**Comment by jasagredo** [comment]
Is the ghcup bin directory on your path? It usually is `C:\ghcup\bin` unless you modified it during the installation.

**Comment by hasufell** [comment]
> it was just my expectation that ghcup set ... would do that for me.

Yes it should. Otherwise it means something is broken.

> ghcup set ghc 9.10

Please specify the FULL GHC version, not just the first two components.

**Comment by fleimgruber** [comment]
> > it was just my expectation that ghcup set ... would do that for me.
> 
> Yes it should. Otherwise it means something is broken.
> 
> > ghcup set ghc 9.10
> 
> Please specify the FULL GHC version, not just the first two components.

Using just the first two version components, the output contains
```
[ Warn  ] Assuming you meant version 9.10.1
[ Info  ] GHC 9.10.1 successfully set as default version
```
which I read as ghcup doing what I was expecting - also a `ghcup tui` confirmed it (i.e. a green "IS" in front of 9.10.1 version).

Anyway, I tried this a few times with removing the ghc.exe and ghc.shim files and it does work now with either `ghcup set ghc 9.10` and `ghcup set ghc 9.10.1` - might have been a hiccup on my side / wrong terminal or something. Sorry for the noise, thanks for the prompt replies and your efforts on ghcup!
