### ISSUE TITLE
Prefer Hadrian

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#259]
In GitLab by @maerwald on Sep 27, 2021, 16:53

1. for cross compilation (needs investigation)
2. for building from bindists (doesn't seem to work yet)
3. for building from git

**Comment by georgefst** [comment]
Out of curiosity, is it documented anywhere why Hadrian is not yet used for cross-compilation? Given that GHCs after 9.0 can't be used with the make system, it's quite a major limitation.

I'm _hoping_ that the work on runtime-retargetability lands soon enough to make this all moot anyway.

**Comment by hasufell** [comment]
> Out of curiosity, is it documented anywhere why Hadrian is not yet used for cross-compilation?

@mpickering @angerman

**Comment by georgefst** [comment]
Oh, so this isn't down to GHCUp at all, upstream just doesn't support it?

**Comment by hasufell** [comment]
Afaik, cross compilation is not "there yet" in hadrian, but I'm not sure if my information is outdated.

**Comment by chreekat** [comment]
It's under active development, although I don't know the exact status of what works and what doesn't. https://gitlab.haskell.org/ghc/ghc/-/issues/?label_name%5B%5D=cross-compilation has a list of related issues.

**Comment by georgefst** [comment]
Looks like this was closed by #844?

**Comment by hasufell** [comment]
> Looks like this was closed by https://github.com/haskell/ghcup-hs/pull/844?

No... this is WIP in https://github.com/haskell/ghcup-hs/pull/854

**Comment by georgefst** [comment]
Ah, my mistake, I was thinking this thread was only re-opened because of the mention of cross-compilation. I missed your second comment and the fact that points 2 and 3 aren't implemented either.

**Comment by hasufell** [comment]
I'll close it in favor of https://github.com/haskell/ghcup-hs/issues/846
