### ISSUE TITLE
.zshrc should be modified upon install

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#312]
In GitLab by @BinderDavid on Jan 11, 2022, 08:12

I just set up a fresh system with Manjaro Linux, which comes with both bash and zsh preinstalled (zsh being the default shell used by console). The system therefore has both `.bashrc` and `.zshrc` configuration files. ghcup correctly offered the possibility to automatically source `.ghcup/env` in `.bashrc`, but it did not offer a similar option for sourcing `.ghcup/env` in `.zshrc`.
I had to do this last step manually, otherwise the binaries are not in the path when opening console. It might be helpful for beginners if the ghcup installer would offer to do this automatically as well.

Related post on stackexchange: https://unix.stackexchange.com/questions/551316/how-do-i-source-in-users-usr-ghcup-env-to-path-in-zshrc-after-installing

PS: Kudos to the developers of ghcup. I recommend your tool to everyone who starts out with Haskell, and the experience working with multiple ghc version has been fantastic!

**Comment by rosshjb** [comment]
There is not even `~/.ghcup/env` file with homebrew installation.

**Comment by hasufell** [comment]
I don't package homebrew, so it's not my cup of tea.
