### ISSUE TITLE
documentation: system dependencies on (Ubuntu) Linux

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#421]
In GitLab by @ulysses4ever on Sep 9, 2022, 22:05

Just this week, I once again had to help a newcomer with setting up the Haskell toolchain on a fresh Ubuntu machine. The issue there is, as it's often the case with newcomers, the system is completely fresh and misses certain system dependencies. I don't see the list of dependencies for such a prolific use case in the User Guide. Would it be possible to add it somewhere? E.g. the Troubleshooting section. I should say the error I saw was quite bizarre (something like "preprocessor sanity check failed" on the configure step for GHC).

As far as I'm aware, this should be enough for Ubuntu (again, a vastly dominant variant of Linux, if include all the flavors and remixes):

```
$ sudo apt update
$ sudo apt install -y build-essential curl libffi-dev libffi7 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5
```

**Comment by ulysses4ever** [comment]
I just noticed that Stack does a very good job at running a system package manager to install dependencies during setup. Maybe you'd want to look at it and possibly copy it. The user is "only" required to `sudo`.

**Comment by hasufell** [comment]
> I just noticed that Stack does a very good job at running a system package manager to install dependencies during setup. Maybe you'd want to look at it and possibly copy it. The user is "only" required to sudo.

Absolutely not.

This goes against the core design principles of GHCup, against unix philosophy and against safety standards (programs invoking sudo can do horrible things).

Also see: https://www.haskell.org/ghcup/about/#non-goals

Package managers are an extremely delicate matter. Invoking them via scripts is bad form and makes them untrustworthy.
