### ISSUE TITLE
Use a `GHCUp` monad

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#437]
In GitLab by @rebeccat on Nov 2, 2022, 10:35

The current code is written in a mix of styles; `mtl` stack, plain `IO`, interspersed with various effect systems. This makes the codebase challenging to work with and extend. We could replace these with a `GHCUp` monad (similar to the [`PandocMonad`](https://hackage.haskell.org/package/pandoc-2.19.2/docs/Text-Pandoc-Class.html#t:PandocMonad) that most of the `pandoc` command-line application is written in).

If this sounds like a good direction, I can work on a merge request. Otherwise, feel free to close.

**Comment by arjunkathuria** [comment]
Revisiting if we'd like to explore an `effectful` re-write in a near-ish long term @hasufell

**Comment by hasufell** [comment]
I'm not sure this is very interesting. GHCup is dealing with mainly one thing: the filesystem. And that *all the time*. We don't really have a lot of interesting abstract effects.

There's a much more interesting thing architecturally, which is:

1. define phases more clearly and then have all installations follow these phases strictly (unpack, configure, compile, install, post-install etc.)
2. the phases are not defined ad-hoc, but are separated from the actual tool installation (this is basically what source package managers do). Recipes (e.g. for GHC) instantiate these phases and the package manager carries them out following certain constraints (e.g. the root filesystem cannot be written to in compile phase).
3. For this, we need a way to filter syscalls, e.g. via seccomp, also see https://github.com/teh/hsseccomp/issues/8

This would be a long way to go to implement a syscall sandbox that works.

But this is real architecture and not just mere monad shuffling.

**Comment by arjunkathuria** [comment]
Apart from the Filesystem (which is the major things ghcup deals with, as you mentioned), We also do Network and quite a lot of error handling.
Our codebase is currently mostly mtl style, with some IO and interspersed ExceptT

A single style through out, with permissions of a functions and the errors that can arise / it handles in it's type signature would probably be a better place to be for the codebase as a whole. (i think we can also spell out the errors, not as a type level lists, like we do currently, but close). I think it would enable more people to read / look and contribute as well, but that's speculation at this point.

Effectful also tends to be a bit faster than mtl according to the benchs on its page but that's not very interesting for us, though it wouldn't hurt.

This, as you mentioned, would just be a refactor and would keep us functionally equivalent, the time spend here, could also be probably used for a more critical feature / architecture / extended platform support, as you mentioned. I wanted to explore the possibility of the scope here and if / or are we even open to it, not immediately, perhaps eventually.

**Comment by hasufell** [comment]
The only real benefit I can see from an effects system is that we could abstract over filesystem operations and then have an in-memory filesystem for testing, because we can choose the interpreter for all the primitives.

However, I'm not a very firm believer in this type of testing. But I'm not opposed to it either.
