### ISSUE TITLE
ghcup installs HLS incompatible with the compiler

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#438]
In GitLab by @rileyrg on Nov 9, 2022, 14:59

running
`curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh`
I get a recommended haskell-language-server default of 1.8.0.0 which isn't compatible with the recommended ghc 9.2.5

**Comment by keithfancher** [comment]
Hello! I was going to started a thread to give some feedback related to the GHCup recommended/default versions here, but this thread seems like an appropriate place to chime in.

Seems like there are a handful of people getting bitten by these defaults... (see https://github.com/haskell/haskell-language-server/issues/3372, for example, or [this reddit thread](https://www.reddit.com/r/haskell/comments/zaq2sn/how_to_set_up_vs_code_for_haskell_on_macos/)).

Since the `recommended` versions seem _most_ useful for beginners, or people without a lot of context about what a given version means, I'd suggest having a stricter set of requirements for making a GHC version `recommended`. Maybe something like:

1. Supported by the HLS
2. Has an associated stackage LTS
3. No known grave bugs :')

So right now that would be, e.g., GHC 9.0.2.

I think this extra bit of stability would really help newcomers, who are being directed to use GHCup (and its recommendations), and wouldn't really get in the way of experienced folks.

Thanks! (And I appreciate the hard work... GHCup is awesome.)

**Comment by hasufell** [comment]
No, 9.0.2 is not an appropriate version. It was a terrible release.

9.2.x is a good release, except that 9.2.4 turned out to be broken on darwin M1 and so we were forced to bump recommended to 9.2.5 as this was an important hotfix release.

'recommended' is already very strict.

Bugfixes > tooling support

**Comment by georgefst** [comment]
> I'd suggest having a stricter set of requirements for making a GHC version `recommended`

This was discussed at https://github.com/haskell/ghcup-hs/issues/412, where there was some productive discussion, but no formal criteria emerged, nor did a consensus that such criteria were helpful or necessary.

> Seems like there are a handful of people getting bitten by these defaults... (see [haskell/haskell-language-server#3372](https://github.com/haskell/haskell-language-server/issues/3372), for example, or [this reddit thread](https://www.reddit.com/r/haskell/comments/zaq2sn/how_to_set_up_vs_code_for_haskell_on_macos/)).

[Another one](https://www.reddit.com/r/haskell/comments/zdj5f0/no_hls_support_for_the_recommended_925/) today. I think it's clear that this is a pretty awkward state of affairs for a lot of novice users, and we should take steps to prevent it from happening again. I agree that the 9.0 series was worth skipping. And it sounds like 9.2.4 had to be left behind. So no one is individually responsible for the issue. There just needs to be better coordination somehow, as @hasufell has said. This strikes me as being the kind of "glue" that the HF (cc @david-christiansen) partly exists to put in place.

**Comment by hasufell** [comment]
> and we should take steps to prevent it from happening again

There's only one way from my side: being even more cautious and waiting at least 1-2 years before bumping 'recommended'. There was a reason I didn't want to move away from 8.10.7 too quickly and it seems my instinct was correct. 

> There just needs to be better coordination somehow

Yes. I said this numerous times. I'm not even notified of upcoming GHC releases. I get to know of them when they are announced on discourse.

Wrt HLS not having done a new release: this is an issue of CI complexity. I've moved to Github because of it and I think HLS will be easier to maintain if releases are executed on Github as well. But that may take some time.

**Comment by georgefst** [comment]
> ghcup installs HLS incompatible with the compiler

FWIW, this is no longer the case, now that HLS 1.9 is out and recommended!

**Comment by blueglyph** [comment]
Just to give some feedback as a newcomer, I find it terribly confusing.

I first installed a recent version of ghc: 9.12.2, but ghcup didn't install any hls-compatible version (it's apparently not available? Not clear, but I guess I have to compile it).

I decided to "update" ghc to 9.6.7, which is pretty old but yet the recommended version. Note that I already have hsl 1.9.0.0, from a `ghcup list`:

```
X  hls   1.8.0.0
IS hls   1.9.0.0
X  hls   1.9.1.0
```

the update, which is fine but complains there is no hls for that version yet (even though it's more than 2 years old) -- note the version 2.9.0.1 it seems to require:
```
503:~ $ ghcup install ghc 9.6.7
[ Warn  ] New cabal version available. If you want to install this latest version, run 'ghcup install cabal 3.14.2.0'
[ Warn  ] New hls version available. If you want to install this latest version, run 'ghcup install hls 2.10.0.0'
[ Info  ] verifying digest of: gs.exe
[ Info  ] downloading: https://downloads.haskell.org/~ghc/9.6.7/ghc-9.6.7-x86_64-unknown-mingw32.tar.xz as file C:\dev\Haskell\ghcup
\tmp\ghcup-02d38d5d0c41fac2\ghc-9.6.7-x86_64-unknown-mingw32.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  309M  100  309M    0     0  5441k      0  0:00:58  0:00:58 --:--:-- 5520k
[ Info  ] verifying digest of: ghc-9.6.7-x86_64-unknown-mingw32.tar.xz
[ Info  ] Unpacking: ghc-9.6.7-x86_64-unknown-mingw32.tar.xz to C:\dev\Haskell\ghcup\tmp\ghcup-77bf0eef469df689
[ Info  ] Installing GHC (this may take a while)
[ Info  ] Merging file tree from "C:\dev\Haskell\ghcup\tmp\ghcup-77bf0eef469df689\ghc-9.6.7-x86_64-unknown-mingw32" to "C:\dev\Haske
ll\ghcup\ghc\9.6.7"
[ Info  ] GHC installation successful
[ Info  ] HLS is not supported for 9.6.7 yet. To build from source, run:
[ ...   ]   ghcup compile hls -g 2.9.0.1 --ghc 9.6.7 --cabal-update -- --constraint="ghc-lib-parser == 9.8.5.20250214" --index-state
="2025-02-14T12:50:38Z"
```
And now setting 9.6.7, which tells me I don't have hls 1.9.0.0, not 2.9.0.1, and despite the fact it is installed?!
```
504:~ $ ghcup set ghc 9.6.7
[ Warn  ] New cabal version available. If you want to install this latest version, run 'ghcup install cabal 3.14.2.0'
[ Warn  ] New hls version available. If you want to install this latest version, run 'ghcup install hls 2.10.0.0'
[ Info  ] verifying digest of: gs.exe
[ Warn  ] GHC-9.6.7 appears to have no corresponding HLS-1.9.0.0 binary.
[ ...   ] Haskell IDE support may not work.
[ ...   ] You can try to either:
[ ...   ]   1. Install a different HLS version (e.g. downgrade for older GHCs)
[ ...   ]   2. Install and set one of the following GHCs: [9.4.4, 9.4.3, 9.2.5, 9.0.2, 8.10.7]
[ ...   ]   3. Let GHCup compile HLS for you, e.g. run: ghcup compile hls -g 1.9.0.0 --ghc 9.6.7 --cabal-update
[ ...   ]      (see https://www.haskell.org/ghcup/guide/#hls for more information)
[ Info  ] GHC 9.6.7 successfully set as default version
```

I tried to find a list of corresponding versions, but without success. It's a bit of a maze to me, and ghcup doesn't seem to install or even agree on which version of hls is required.
