### ISSUE TITLE
Document how to manually install ghcup on windows

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#697]
If the powershell script fails, people are usually left wondering how to do things manually.

Usually this involves:

1. download correct ghcup binary and put it in the right location
2. set `GHCUP_INSTALL_BASE_PREFIX` env var correctly (can be omitted if user puts the binary into `C:\ghcup\bin`)
3. download correct msys2 distribution and install it
4. set `GHCUP_MSYS2` env var correctly
5. set `CABAL_DIR` env var correctly (we can do without this var, but then need to figure out where the cabal config location actually is...)
6. install cabal via ghcup
7. run `cabal update`
8. adjust `$CABAL_DIR/cabal.config`
    - set `extra-prog-path`, `extra-lib-dirs` and `extra-include-dirs` correctly to include msys2 dirs

This should all be properly documented on the homepage.

**Comment by develop7** [comment]
Looks like the current approach requires us to maintain largely similar bootstrap scripts in bash & powershell at least; did anyone try implementing bootstrapper in haskell as well? This way the script would only download proper bootstrapping binary and run it, making it way simpler to maintain.

**Comment by hasufell** [comment]
> Looks like the current approach requires us to maintain largely similar bootstrap scripts in bash & powershell 

Not really. The powershell script deals with different things (setting up msys2) and calls the bash script in fact.

> did anyone try implementing bootstrapper in haskell as well?

I don't think there's much use in it.
