### ISSUE TITLE
Full URIs prevent mirrors from distributing signed metadata

### ISSUE THREAD

**Issue by kylerky** [haskell/ghcup-hs#704]
Metadata files include full URIs of the downloads. However, mirrors need to change the URIs in order to direct GHCup to the mirror sites, which invalidates the signatures of the metadata files.

A possible solution is to use relative paths in metadata and to allow users to specify a base URI for their downloads.

**Comment by hasufell** [comment]
Duplicate: https://github.com/haskell/ghcup-hs/issues/357

There's already a PR: https://github.com/haskell/ghcup-hs/pull/700
