### ISSUE TITLE
GHCup initial installer gives incorrect advice

### ISSUE THREAD

**Issue by ChaiTRex** [haskell/ghcup-hs#705]
I ran `curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh` and had to stop it. When I reran it, I got the following messages:

    [ Warn  ] ghc-9.2.5 is already installed; if you really want to reinstall it, you may want to run 'ghcup install cabal --force 9.2.5'
    [ Info  ] GHC 9.2.5 successfully set as default version
    [ Warn  ] cabal-3.6.2.0 is already installed; if you really want to reinstall it, you may want to run 'ghcup install cabal --force 3.6.2.0'

It seems like the first line there should suggest something like `ghcup install ghc --force 9.2.5` with `ghc` instead of `cabal`.

**Comment by hasufell** [comment]
This is already fixed in https://github.com/haskell/ghcup-hs/commit/63dfdc2da6b7789a8eeccd508154f44ed5f263b6

But not released.
