### ISSUE TITLE
`OwnSource` setting lost after `ghcup config add-release-channel`

### ISSUE THREAD

**Issue by ksqsf** [haskell/ghcup-hs#708]
Suppose I have the following config,

```
url-source:
  OwnSource: xxx
```

Then run the following command,

```
ghcup config add-release-channel yyy
```

Now the `OwnSource` entry disappears,

```
url-source:
  AddSource:
  - Right: yyy
```

Consequently, the "main" source will not be `xxx`, but the default one.

**Comment by ksqsf** [comment]
https://github.com/haskell/ghcup-hs/blob/823458910b41cf79739257dbc3d08084400bb594/app/ghcup/GHCup/OptParse/Config.hs#L189

It seems that `add-release-channel` just adds the release channel to the default config. Is this by design?

**Comment by hasufell** [comment]
It's a recent feature. I'm willing to make it more robust. PRs also welcome.

The type is here:

https://github.com/haskell/ghcup-hs/blob/823458910b41cf79739257dbc3d08084400bb594/lib/GHCup/Types.hs#L290-L294

So `OwnSource` accepts a list and we could just append to it. `OwnSpec` could be turned into `OwnSource`. I've just kept it for backwards compatibility in fact.
