### ISSUE TITLE
Arch (manjaro) linux:  checking for ar

### ISSUE THREAD

**Issue by appomsk** [haskell/ghcup-hs#709]
I couldn't install ghc. From ghc-configure.log:

```
checking whether ar is GNU ar... no
checking for ar arguments... configure: error: cannot figure out how to use your ar
```

My ar:

```
$ which -a ar
/usr/bin/ar

$ ar --version
GNU ar (GNU Binutils) 2.39.0
...
```

**Comment by hasufell** [comment]
Just tried in a manjaro docker container. I cannot reproduce.

**Comment by appomsk** [comment]
I now looked more closely. My `sh` was busybox shell in my home `~/bin`. And it has its own `ar`.  Sorry

**Comment by appomsk** [comment]
`ghcup` invoked `sh` with `configure` as argument. And my `sh` was busybox `sh` with its own `ar`.
