### ISSUE TITLE
Installation of GHC does not work on Red Hat Enterprise Linux 8

### ISSUE THREAD

**Issue by athas** [haskell/ghcup-hs#710]
This is more of a tracking issue and reference for other users, because I don't know what ghcup can do about this.

RHEL 8 doesn't come with libtinfo5 anymore (it has libtinfo6), so the RHEL 7 tarballs installed by ghcup do not work.  I don't know whether any of the upstream tarballs do - certainly the Debian ones do not.

**Comment by hasufell** [comment]
So, the same issue exists on Fedora 37, because an overly smart packager didn't understand what binary compatibility means. This issues is for older GHCs there only.

@juhp

**Comment by juhp** [comment]
Btw what's the oldest ghc version supported for building ghc?

**Comment by hasufell** [comment]
> Btw what's the oldest ghc version supported for building ghcup?

8.10.7

**Comment by juhp** [comment]
(Okay I am pretty behind in EPEL 8: currently only 8.2.2 but I would like to some newer GHC's)

**Comment by athas** [comment]
The fedora27 upstream tarball works for me:

```
ghcup install ghc --set -p x86_64-fedora27-linux
```

**Comment by josephcsible** [comment]
RHEL9 has this problem too, and there doesn't appear to be an official Fedora 27 binary anymore for GHC 9.4 or later, but at least the Fedora 33 binary (`-p x86_64-fedora33-linux`) seems to work. I saw a Rocky 8 one too, but since the first one worked I didn't bother to try it.

**Comment by juhp** [comment]
Btw there are also "official" downstream ghc builds for RHEL9 in the EPEL repo: ghc8.10, ghc9.0, ghc9.2, ghc9.4, and ghc9.6

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-metadata/pull/89

Try this:

```sh
ghcup -s https://raw.githubusercontent.com/haskell/ghcup-metadata/2dbfc84ef6b4f6e7ec9470afa432df384d6c22e8/ghcup-0.0.7.yaml --metadata-caching=0
tui
```

And then install some versions.

**Comment by athas** [comment]
That works for me, but what does `-s` do?  It is not listed in `ghcup --help`.

**Comment by ulysses4ever** [comment]
@hasufell would an issue about `--help` lacking description of `-s` be welcome? It feels like a rather serious omission. I for one have seen (and perhaps used) it many times and felt completely clueless about it. I just never realized that.

**Comment by hasufell** [comment]
> @hasufell would an issue about `--help` lacking description of `-s` be welcome? It feels like a rather serious omission. I for one have seen (and perhaps used) it many times and felt completely clueless about it. I just never realized that.

Sure.

**Comment by hasufell** [comment]
red hat installation fix was merged
