### ISSUE TITLE
Installing GHC via GHCup: C compiler cannot create executables

### ISSUE THREAD

**Issue by anafvana** [haskell/ghcup-hs#728]
When trying to install GHC via GHCup on an M1 Mac, I get an error claiming the C compiler cannot create executables.

<details>
  <summary>GHCup tui output</summary>

```
[ Info  ] Installing GHC (this may take a while)
[ ghc-configure ] configure: Xcode version component 2: 2
[ ghc-configure ] checking for gcc... gcc
[ ghc-configure ] checking whether the C compiler works... no
[ ghc-configure ] configure: error: in `/Users/a/.ghcup/tmp/ghcup-c7d0c1d07e7d2113/ghc-8.10.7':
[ ghc-configure ] configure: error: C compiler cannot create executables
[ ghc-configure ] See `config.log' for more details
Error: Process "sh" with arguments ["./configure",
                             "--prefix=/Users/a/.ghcup/ghc/8.10.7",
                             "--disable-ld-override"] failed with exit code 77.
Also check the logs in ~/.ghcup/logs
```
</details>

## Info
**MacOS**
13.0.1 (22A400)

**GCC**
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**LLVM**
12.0.1

**XCode**
Xcode 14.2
Build version 14C18

### C compiler

**Test**: Wrote a simple C program, compiled it and executed successfully. 

Result: **No errors**. The C compiler CAN, in fact, create executables.

Observation: It is not a permissions issue either. The `.c` file was created and compiled within the `.ghcup` folder

### GHCup

**Test 1**: Attempting to install other versions of GHC

Result 1: **Failed**. No GHC version would install, all with the same C compiler error.

**Test 2**: Attempting to install other tools (cabal, stack, etc)

Result 2: **No errors**. Everything was successfully installed, except for GHC

**Test 3**: Attempting to install GHCup for x86_64 architecture.

<details>
  <summary>Steps to reproduce test 3</summary>

N.B.: My goal was to have an entirely isolated environment

1. Create x86_64 instance of Homebrew and alias brew-x86_64
```
$ sudo mkdir /usr/local/opt
$ sudo chown <your_user>:staff /usr/local/opt
$ git clone git@github.com:Homebrew/brew.git
$ ln -s /usr/local/opt/brew/bin/brew /usr/local/opt/brew/bin/brew-x86_64
```

2. [OPTIONAL] Add `/usr/local/opt/brew/bin` to PATH (added to .bashrc)

3. Install GHCup for x86_64
```
$ arch -x86_64 /usr/local/opt/brew/bin/brew-x86_64 install ghcup
```
</details>

Result 3: **Same as tests 1 and 2**. GHCup successfully installed. Stack, HLS, cabal, etc. successfully installed via GHCup. GHC failed to install, same compiler error.

### GHC

**Test 1**: Install GHC from Homebrew

Result 1: **No errors**. GHC successfully installed

**Test 2**: Install GHC from Homebrew x86_64 instance

<details>
  <summary>Steps to reproduce test 2</summary>

```
$ arch -x86_64 /usr/local/opt/brew/bin/brew-x86_64 install ghc@8.10
```
</details>

Result 2: **No errors**. GHC successfully installed

## Hacky solution

After much trial and error, I found that, I could bypass the `C compiler cannot create executables` error by running the following command before attempting to install GHC:

```
export CFLAGS="-arch arm64 ${CFLAGS:-}"
```

I assume, however, that this is not intended behaviour, otherwise it would've been specified in the documentation.

**Comment by hasufell** [comment]
```hs
$ arch -x86_64 /usr/local/opt/brew/bin/brew-x86_64 install ghcup
```

Please install ghcup via the official method: `curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh`

I don't give support to installing via brew. Contact your brew maintainers for that.

**Comment by anafvana** [comment]
Seems to have been a problem with Homebrew!

Just nuked everything and reinstalled with `curl` and it seems to work perfectly now. Thank you so much!
