### ISSUE TITLE
Allow overriding directories when using $GHCUP_USE_XDG_DIRS

### ISSUE THREAD

**Issue by MithicSpirit** [haskell/ghcup-hs#729]
See title. Specifically, I'd like to override what is used for `$XDG_BIN_HOME`.

**Comment by hasufell** [comment]
https://www.haskell.org/ghcup/guide/#xdg-support

I don't understand your question. Just override it?

**Comment by MithicSpirit** [comment]
Oh I meant that I want to override it specifically for ghcup without affecting other programs, so for example a `$GHCUP_BINS` envvar (or maybe a config option). While I could manually change the envvar for ghcup on each invocation (e.g. `XDG_BIN_HOME="$HOME/.local/bin/ghcup" ghcup`), that seems like a hassle and does not work if other programs attempt to execute ghcup.

**Comment by hasufell** [comment]
> that seems like a hassle

You can use bash aliases for that.

**Comment by hasufell** [comment]
> does not work if other programs attempt to execute ghcup

You can use a shell wrapper and rename ghcup to `ghcup.bin` and call it from the shell wrapper. Then make sure to upgrade via `ghcup upgrade --inplace`.

**Comment by MithicSpirit** [comment]
Yeah, I guess that works. Seems a bit inelegant though, and I think that it would be nicer to have special envvars for this.

**Comment by hasufell** [comment]
> Yeah, I guess that works. Seems a bit inelegant though, and I think that it would be nicer to have special envvars for this.

I think this use case is fairly non-standard. In fact, I'd rather remove XDG support, because it doesn't work very well for ghcup. GHCup assumes some binary names and version conventions and can get confused if arbitrary binaries are in the bindir like `cabal-cache`.

Yes, it can be considered a bug, but yeah.
