### ISSUE TITLE
URI parsing replaces + with a space

### ISSUE THREAD

**Issue by mpickering** [haskell/ghcup-hs#742]
In a custom metadata file, I have a URL which contains a +, when this is parsed by the `FromJSON` instance into a URI. The parsing succeeds but the `+` is placed by a ` `.  I'm not sure exactly why this happens but I suppose it should fail during parsing?

```
https://gitlab.haskell.org/ghc/ghc/-/jobs/1287991/artifacts/raw/ghc-x86_64-linux-alpine3_12-int_native-validate+fully_static.tar.xz
```

is parsed into

```
URI {uriScheme = Scheme {schemeBS = "https"}, uriAuthority = Just (Authority {authorityUserInfo = Nothing, authorityHost = Host {hostBS = "gitlab.haskell.org"}, authorityPort = Nothing}), uriPath = "/ghc/ghc/-/jobs/1287991/artifacts/raw/ghc-x86_64-linux-alpine3_12-int_native-validate fully_static.tar.xz", uriQuery = Query {queryPairs = []}, uriFragment = Nothing})
```

Notice that the final `+` is replaced by a ` `.

**Comment by hasufell** [comment]
Please comment in #408

**Comment by mpickering** [comment]
Yes thanks #408 is good information. I have encoded the relevant parts of the URL now and that works.
