### ISSUE TITLE
ghcup-0.1.19.0 is busted on windows

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#745]
Users report on windows the ghcup binary fails to start with **libstdc++-6.dll is missing**.

```
$ ldd x86_64-mingw64-ghcup-0.1.19.0.exe
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7ffb81bd0000)
        KERNEL32.DLL => /c/Windows/System32/KERNEL32.DLL (0x7ffb80350000)
        KERNELBASE.dll => /c/Windows/System32/KERNELBASE.dll (0x7ffb7f470000)
        ADVAPI32.dll => /c/Windows/System32/ADVAPI32.dll (0x7ffb80410000)
        msvcrt.dll => /c/Windows/System32/msvcrt.dll (0x7ffb81880000)
        sechost.dll => /c/Windows/System32/sechost.dll (0x7ffb810d0000)
        RPCRT4.dll => /c/Windows/System32/RPCRT4.dll (0x7ffb813b0000)
        GDI32.dll => /c/Windows/System32/GDI32.dll (0x7ffb80f70000)
        win32u.dll => /c/Windows/System32/win32u.dll (0x7ffb7f890000)
        gdi32full.dll => /c/Windows/System32/gdi32full.dll (0x7ffb7fb00000)
        msvcp_win.dll => /c/Windows/System32/msvcp_win.dll (0x7ffb7fa60000)
        ucrtbase.dll => /c/Windows/System32/ucrtbase.dll (0x7ffb7f8f0000)
        USER32.dll => /c/Windows/System32/USER32.dll (0x7ffb81600000)
        ole32.dll => /c/Windows/System32/ole32.dll (0x7ffb801e0000)
        combase.dll => /c/Windows/System32/combase.dll (0x7ffb804c0000)
        SHELL32.dll => /c/Windows/System32/SHELL32.dll (0x7ffb80820000)
        SHLWAPI.dll => /c/Windows/System32/SHLWAPI.dll (0x7ffb80fa0000)
        WS2_32.dll => /c/Windows/System32/WS2_32.dll (0x7ffb81810000)
        libstdc++-6.dll => not found
        dbghelp.dll => /c/Windows/SYSTEM32/dbghelp.dll (?)
        WINMM.dll => /c/Windows/SYSTEM32/WINMM.dll (?)
```

Probably due to text-2.0 forcing us to link against `libstdc++-6.dll`.

@Bodigrim @mpickering @bgamari how are distributors supposed to ship portable binaries with text-2.0?

**Comment by hasufell** [comment]
I was able to hack around it by adding `C:\ghcup\ghc\9.2.5\mingw\bin` to my windows `Path`.

**Comment by mpickering** [comment]
I think for now, the best thing to do is build text without depending on C++ as (by setting flag `-simdutf`).

**Comment by hasufell** [comment]
Hotfix pipeline: https://github.com/haskell/ghcup-hs/actions/runs/3913015753/jobs/6688387997

**Comment by hasufell** [comment]
That didn't work, second try: https://github.com/haskell/ghcup-hs/actions/runs/3913314508

**Comment by hasufell** [comment]
@mpilgrem a big fat warning to you. I'm not how or if stackage deals with this or if it's still pre text-2.0. Using simdutf on text-2.0 (which is the default), will make all your binaries non-portable.

**Comment by mpilgrem** [comment]
@hasufell, thanks for the heads-up. Stack is currently built with GHC 9.2.5 and `text-1.2.5.0` (which comes with GHC 9.2.5), but I am keen to move it on to GHC 9.4 (GHC 9.4.4 comes with `text-2.0.1`) as soon as there is a Stackage LTS Haskell for GHC 9.4.

**Comment by mpilgrem** [comment]
Actually, the current Stack is also buildable with GHC 9.4.4 (Stackage `nightly-2023-01-13`, dependency on `text-2.0.1`). I don't know what I am doing 'wrong' but it builds fine, and the built executable runs fine, on Windows 11.

**Comment by hasufell** [comment]
> Actually, the current Stack is also buildable with GHC 9.4.4 (Stackage `nightly-2023-01-13`, dependency on `text-2.0.1`). I don't know what I am doing 'wrong' but it builds fine, and the built executable runs fine, on Windows 11.

GHC has disabled simdutf when it's used as a boot library. I built text-2.0 with GHC 8.10.7.
