### ISSUE TITLE
Is v0.21 the latest release?

### ISSUE THREAD

**Issue by p-linnane** [haskell/ghcup-hs#749]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. We are trying to build `ghcup` 0.21 and enountering failures. We noticed that 0.1.19.2 is still marked as the latest release on GitHub. Is that still accurate? If so we will rebuild 0.1.19.2 with ghc 9.4.4 and mark it as latest. Thanks!

https://github.com/Homebrew/homebrew-core/pull/120608

**Comment by hasufell** [comment]
The latest release ia 0.1.19.0.

**Comment by p-linnane** [comment]
Thank you.
