### ISSUE TITLE
Too many downloads of https://githubusercontent.com/haskell/ghcup-metadata/master/ghcup-0.0.7.yaml ?

### ISSUE THREAD

**Issue by andreasabel** [haskell/ghcup-hs#778]
Lifted from:
- https://github.com/haskell/actions/issues/187

Just these day setting up GHC on CI through `ghcup` via `haskell/actions/setup` started failing a lot for me.  Before `ghcup` starts installing GHC, it downloads https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-0.0.7.yaml and when this fails we see error: 
```
ghcup: /usr/local/.ghcup/cache/ghcup-0.0.7.yaml: 
setModificationTime:setFileTimes: permission denied (Operation not permitted)
```
This download failure leads to failure of ghcup -> setup -> CI workflow.  Rerunning the workflow sometimes helps.

Just a wild guess, but maybe `githubusercontent.com` refuses to respond to the download request in fear of a DoS attack, or it is just overloaded.  In any case we should watch this issue and see if it goes away.

Is there a known workaround this problem?

Maybe a version of `ghcup-*.yaml` could be shipped with `ghcup`, and download could be skipped on demand?  E.g. if I install an "old" GHC version, I wouldn't necessarily need the latest `ghcup-*.yaml`.

`raw.githubusercontent.com` seems to have a rate limit (5000/hour/IP address) (but I'd be surprised with many action runners share the same IP address):
- https://stackoverflow.com/questions/66522261/does-github-rate-limit-access-to-public-raw-files

**Comment by hasufell** [comment]
https://discourse.haskell.org/t/incident-github-actions-ci-failure-ghcup/5761?u=hasufell

**Comment by hasufell** [comment]
> Maybe a version of ghcup-*.yaml could be shipped with ghcup, and download could be skipped on demand? E.g. if I install an "old" GHC version, I wouldn't necessarily need the latest ghcup-*.yaml.

I thought about it, but mirrors seem to be a better way to solve this.

**Comment by andreasabel** [comment]
Thanks for solving this riddle for me, I reposted your discord message in the `haskell/action/setup` issue!
