### ISSUE TITLE
Very recent `windows-2022`: has location of `ghcup` changed?

### ISSUE THREAD

**Issue by andreasabel** [haskell/ghcup-hs#783]
`haskell/action/setup` no longer finds `ghcup` on the `windows-2022` virtual environment of 14 Feb 2023.
It seems to expect `ghcup` at `C:\hostedtoolcache\windows\ghcup\0.1.19.0\x64\ghcup`.

@hasufell : Before I upstream this further, I thought I ask you whether `haskell/action/setup` is to be blamed here by searching for `ghcup` in the wrong location.  Has anything changed recently concerning this location on the `windows-2022` virtual environment.

Upstreamed from:
- https://github.com/haskell/actions/issues/191

https://github.com/haskell/primitive/actions/runs/4202068611/jobs/7289771094#step:1:9
> Runner Image
>   Image: windows-2022
>   Version: 20230214.1

https://github.com/haskell/primitive/actions/runs/4202068611/jobs/7289771094#step:3:13
> Adding ghcup release channel: https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-prereleases-0.0.7.yaml
> Error: Unable to locate executable file: C:\hostedtoolcache\windows\ghcup\0.1.19.0\x64\ghcup. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

**Comment by hasufell** [comment]
Yes, there was a recent change. Windows runners no longer use chocolatey, but ghcup to install GHC.

https://github.com/actions/runner-images/pull/6754
