### ISSUE TITLE
GHCup-00080 Failed to merge file tree, trying to upgrade to HLS 1.9.1.0

### ISSUE THREAD

**Issue by rubin55** [haskell/ghcup-hs#787]
Using The GHCup Haskell installer, version 0.1.19.1

```
Error: [GHCup-00080] Failed to merge file tree from /home/rubin/.ghcup/tmp/ghcup-ad18ce76d856d0e9/home/rubin/.ghcup/hls/1.9.1.0 to /home/rubin/.ghcup/hls/1.9.1.0 
exception was: /home/rubin/.ghcup/tmp/ghcup-ad18ce76d856d0e9/home/rubin/.ghcup/hls/1.9.1.0/bin: install: not a regular file or symlink: illegal operation 
...you may need to delete /home/rubin/.ghcup/hls/1.9.1.0 manually. Make sure it's gone.
Also check the logs in ~/.ghcup/logs
Press enter to continue
```

Log files:
  * [ghc-make.log](https://github.com/haskell/ghcup-hs/files/10782445/ghc-make.log)
  * [ghcup.log](https://github.com/haskell/ghcup-hs/files/10782446/ghcup.log)
  * [ghcup-tui.log](https://github.com/haskell/ghcup-hs/files/10782449/ghcup-tui.log)

This happened when trying to upgrade to HLS 1.9.1.0. This is on JFS, so maybe this is a regression, see #766.

**Comment by hasufell** [comment]
We'll have to write a CI test for this.

**Comment by rubin55** [comment]
For what it's worth, the test version mentioned [here](https://github.com/haskell/ghcup-hs/issues/766#issuecomment-1416797484) works correctly, so this is specific to 0.1.19.1.

**Comment by hasufell** [comment]
Found it: https://github.com/haskell/ghcup-hs/commit/6d3e8d65e148e205cd5c0f8227d1d91cd04312a4#diff-2d9015010bcf8511a8be4190d7203f50fea2ce7f5b04d3f2d44bea2b93914ce1R127

**Comment by hasufell** [comment]
@rubin55 I'll ping you during the next release (prolly this weekend) for testing, ok?

**Comment by rubin55** [comment]
@hasufell Of course, let me know if I need to test some stuff. Much appreciated!

**Comment by hasufell** [comment]
released https://github.com/haskell/ghcup-hs/releases/tag/v0.1.19.2
