### ISSUE TITLE
Can `latest` apply to prereleases too?

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/ghcup-hs#788]
Perhaps, not `latest` but something else (`latest-prerelease`?), I don't care about a particular word, I just want a generic name, so that I don't haveto memoize all that 9.6.0.xyzabc business..

**Comment by hasufell** [comment]
We definitely need a succint name for the tag. `latest-prerelease` sounds ok to me.

This will require code changes.

Any motivation for a PR?

**Comment by ulysses4ever** [comment]
I’m afraid I’m overcommitted currently :-(

**Comment by hasufell** [comment]
Released https://github.com/haskell/ghcup-hs/releases/tag/v0.1.19.2
