### ISSUE TITLE
Consider using brick-tabular-list and brick-list-search.

### ISSUE THREAD

**Issue by amano-kenji** [haskell/ghcup-hs#794]
I wrote them.

brick-tabular-list contains mixed tabular list widget which can look like this.

![mpv-shot0001](https://user-images.githubusercontent.com/106365348/220629000-e12c69fd-301f-4dda-818a-13eb81a0bd6f.png)

To make mixed tabular list look like this, the height of column headers should be 2, and the second line for column header row header and each column header should be filled with `hBorder`. Adjacent horizontal borders will be joined automatically.

brick-list-search can skip separators if separators were list elements. It can also show separators at the top and the bottom. The demo program shows how to show them at the top and the bottom.

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-hs/blob/master/app/ghcup/BrickMain.hs

Do you want to take a stab at it? It's really not much code.

**Comment by amano-kenji** [comment]
I am tempted to take up the challenge. Unfortunately, I'm running out of time.

I implemented brick-tabular-list and brick-list-search because I had to. I was not going to move forward without them.

**Comment by amano-kenji** [comment]
While brick-tabular-list won't necessarily improve ghcup codebase, I argue that brick-list-search will.

The current ghcup codebase breaks brick list's scrolling mechanism because it breaks the invariant that every list element should have the same number of lines.

**Comment by amano-kenji** [comment]
And, I want people to actually understand my library. If I use my libraries in other people's codes, they won't understand their own codebase.
