### ISSUE TITLE
Windows installation issues

### ISSUE THREAD

**Issue by blueglyph** [haskell/ghcup-hs#795]
I installed GHCup with the following command in the powershell:

```powershell
Set-ExecutionPolicy Bypass -Scope Process -Force;[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; try { Invoke-Command -ScriptBlock ([ScriptBlock]::Create((Invoke-WebRequest https://www.haskell.org/ghcup/sh/bootstrap-haskell.ps1 -UseBasicParsing))) -ArgumentList $true } catch { Write-Error $_ }
```

and noticed the following issues:

- icons are put on the desktop without asking the user, instead of being stored in the menu:
![image](https://user-images.githubusercontent.com/31706195/220742078-b46e0a31-9b5b-4c1e-b963-c388a4640cfb.png)

For people who are trying to keep the desktop clean, it's not really friendly. Besides, it's safer to store links into the Windows menu - it's what it's there for. It also allows quick launching items. Note also how some of the names are so long they can't be read.

- the `ghcup tui` shown on the installation page doesn't seem to work, I assume it's something to install separately (I only tried it because that page is luring users to try it)

```
>ghcup tui
Invalid argument `tui'

Did you mean this?
    run
```

- I used `ghcup list` instead and the versions seem old, I got the following warnings:

```
[ Warn  ] New ghc version available. If you want to install this latest version, run 'ghcup install ghc 9.4.4'
[ Warn  ] New cabal version available. If you want to install this latest version, run 'ghcup install cabal 3.8.1.0'
[ Warn  ] New hls version available. If you want to install this latest version, run 'ghcup install hls 1.9.1.0'
```
So right after a fresh install, I had to re-install those components, is there a reason why it's not directly the latest recommended versions?

The advice given by `ghcup list` is misleading for new users too: `run ghcup install ghc 9.4.4` - which I did, only to realize it wasn't the recommended version (9.2.5), so I had to re-install it a 3rd time. Not a warm welcome. 😉

**Comment by hasufell** [comment]
> For people who are trying to keep the desktop clean, it's not really friendly. Besides, it's safer to store links into the Windows menu - it's what it's there for. It also allows quick launching items. Note also how some of the names are so long they can't be read.

We can ask, but keep in mind that every single user out there will now to have to answer this question, when maybe 1% cares about it.

You can simply delete the icons.

> the ghcup tui shown on the installation page doesn't seem to work, I assume it's something to install separately (I only tried it because that page is luring users to try it)

TUI is not available on windows yet.

See https://github.com/haskell/ghcup-hs/issues/208

> So right after a fresh install, I had to re-install those components, is there a reason why it's not directly the latest recommended versions?

Yes, we install recommended by default, not latest. There's nothing to reinstall. GHCup simply notifies you that there are more recent versions.

See https://www.haskell.org/ghcup/install/#which-versions-get-installed

> The advice given by ghcup list is misleading for new users too: run ghcup install ghc 9.4.4 - which I did, only to realize it wasn't the recommended version (9.2.5), so I had to re-install it a 3rd time. Not a warm welcome.

This is incorrect. 9.2.5 is already installed. There's nothing to reinstall. I don't know where you get this idea from. You have both 9.4.4 and 9.2.5 and can switch between them via `ghcup set`.

**Comment by blueglyph** [comment]
> We can ask, but keep in mind that every single user out there will now to have to answer this question, when maybe 1% cares about it.
> 
> You can simply delete the icons.

Not sure where you saw those statistics, I know many people who are bothered by it. It remains that the logical place is in the menu, it's rare that an app doesn't store the shortcuts there. It also solves the problem of asking. It was just a suggestion.
 
> > So right after a fresh install, I had to re-install those components, is there a reason why it's not directly the latest recommended versions?
> 
> Yes, we install recommended by default, not latest. There's nothing to reinstall. GHCup simply notifies you that there are more recent versions.

That's strange, I'm pretty sure it was a much older version. In any case, a warning is a message informing of something that should be taken care of, that's what mislead me.

> 
> This is incorrect. 9.2.5 is already installed. There's nothing to reinstall. I don't know where you get this idea from. You have both 9.4.4 and 9.2.5 and can switch between them via `ghcup set`.

I get that idea from the long downloading time it took to install each of them.

**Comment by blueglyph** [comment]
I'll just close it, I don't think it's worth pursuing this. Thanks for your replies.
