### ISSUE TITLE
When showing changelog info for any tool in TUI, warning for stray directory ".DS_Store" shows up in terminal

### ISSUE THREAD

**Issue by 0rphee** [haskell/ghcup-hs#797]
If I use the command to see the changelong for any tool version in the TUI, the following warning is printed:

```
[ Warn  ] Could not parse version of stray directory.DS_Store
[ Warn  ] Could not parse version of stray directory.DS_Store
Press enter to continue
```

`.DS_Store` is a file in macOS that stores information about the folder that contains it. I am ignorant, but I don't see a reason to be warned about the version of that.

**Comment by hasufell** [comment]
You can remove it and run

```
defaults write com.apple.desktopservices DSDontWriteNetworkStores true
```

I may need to patch ghcup to ignore them.

**Comment by 0rphee** [comment]
Should I close this issue then? There may be people that for some reason won't want to run that command.

**Comment by hasufell** [comment]
I'll fix it with next point release.

**Comment by hasufell** [comment]
Released https://github.com/haskell/ghcup-hs/releases/tag/v0.1.19.2
