### ISSUE TITLE
FreeBSD 13.1 installation fails

### ISSUE THREAD

**Issue by avysk** [haskell/ghcup-hs#804]
Apparently, `ghc` depends on `libnursesw.8.so`, which is not available. However, the library can be installed with `compat12x-amd64-12.2.1202000.20210406` package, and it fixes the installation. Until `ghc` is fixed, the installation documentation should be updated.

<img width="658" alt="image" src="https://user-images.githubusercontent.com/130091/223382755-3e39012f-7885-408b-916f-525ebe857c5b.png">

**Comment by hasufell** [comment]
Which GHC?

**Comment by avysk** [comment]
Obviously, the one `ghcup` installs by default: `9.2.5`.
```
❯ ldd ~/.ghcup/ghc/9.2.5/lib/ghc-9.2.5/bin/ghc | grep curses
        libncursesw.so.8 => /usr/local/lib/compat/libncursesw.so.8 (0x8080f6000)
```

**Comment by hasufell** [comment]
Can you try 9.2.7?

**Comment by avysk** [comment]
Sure, a moment.

**Comment by avysk** [comment]
Looks good.
```
❯ ldd ~/.ghcup/ghc/9.2.7/lib/ghc-9.2.7/bin/ghc | grep curses
        libncursesw.so.9 => /lib/libncursesw.so.9 (0x80744b000)
```

**Comment by hasufell** [comment]
9.2.7 will be the default version soon, then it will fix itself

**Comment by avysk** [comment]
The problem is that it probably won't work on FreeBSD 12 which is still a production release according to www.freebsd.org

**Comment by hasufell** [comment]
I only support FreeBSD 13.x and that's already hard as it is, because GHC has no official support anymore. I build the bindists myself.

**Comment by avysk** [comment]
Should the docs mention it is 13 only?

**Comment by hasufell** [comment]
https://www.haskell.org/ghcup/install/#freebsd_1

Feel free to create a PR that updates the description.

**Comment by avysk** [comment]
There was some problem in CI, but surely not caused by my editing of markdown: `.github/scripts/common.sh: line 18: S3_HOST: unbound variable`
