### ISSUE TITLE
ghcup doesn't run on centos 7

### ISSUE THREAD

**Issue by brandonchinn178** [haskell/ghcup-hs#812]
Installing/running the ghcup executable itself on Centos 7 shows "error while loading shared libraries: libtinfo.so.6"

Maybe the "Supported Platforms" page should be updated?

If it helps, I'm on Centos 7 aarch64

**Comment by hasufell** [comment]
> If it helps, I'm on Centos 7 aarch64

On aaarch64, we build in debian 10. And that's where the GHC bindists are built as well. So even if ghcup would work on it, the GHC bindists won't.

**Comment by brandonchinn178** [comment]
Yes, I just discovered that too 😥

But it seems like the particular issue here isn't just for aarch64; I would think (but haven't checked) the same issue would happen for CentOS 7 x86_64

**Comment by hasufell** [comment]
> I would think (but haven't checked) the same issue would happen for CentOS 7 x86_64

No

**Comment by brandonchinn178** [comment]
I see. The x86_64 binaries are statically compiled and the aarch64 ones are dynamically compiled?
