### ISSUE TITLE
`ghcup tui` coredumps after removing ghc 9.2.5

### ISSUE THREAD

**Issue by geekosaur** [haskell/ghcup-hs#816]
Sadly this ubuntu system eats coredumps because I haven't yet worked out how to disable the crash reporter.

I upgraded HLS to 1.10.0.0, then installed ghc 9.2.7, set it, and removed ghc 9.2.5. After the latter, it asked me to press return, then hung for several seconds, then aborted; zsh reported that it had caught a segmentation fault.

**Comment by geekosaur** [comment]
OS: Ubuntu 20.04
ghcup version: 0.1.19.2

**Comment by hasufell** [comment]
I think I hit that too yesterday. 

Is it reproducible?

**Comment by geekosaur** [comment]
I'm reinstalling 9.2.5 to see if it reproduces.

I just noticed that it never actually marked 9.2.5 as deleted in the TUI. Telling it to delete again succeeded very quickly.

**Comment by geekosaur** [comment]
I re-added and then re-removed 9.2.5 and it didn't crash. I might have to retry the whole sequence of actions starting with upgrading HLS.

**Comment by 0rphee** [comment]
I think something similar happened to me. 

I tried to do the same (uninstall 9.2.5, install 9.2.7, and hls 1.10.0.0). I think while removing 9.2.5, something happened, and the cleanup didn't finish correctly (I'm not sure, since I didn't actively check that, just assumed it went correctly), and while trying to compile a proyect with 9.2.7 this error came out:

```
(...)
brick                        > Installing executable brick-visibility-demo in /Users/roger/.stack/snapshots/aarch64-osx/4ffc2b29c12b3cae23c7a379a242de88e376f2e6d9da6f32712764d789c302af/9.2.7/bin
brick                        > Installing executable brick-viewport-scroll-demo in /Users/roger/.stack/snapshots/aarch64-osx/4ffc2b29c12b3cae23c7a379a242de88e376f2e6d9da6f32712764d789c302af/9.2.7/bin
brick                        > Installing executable brick-progressbar-demo in /Users/roger/.stack/snapshots/aarch64-osx/4ffc2b29c12b3cae23c7a379a242de88e376f2e6d9da6f32712764d789c302af/9.2.7/bin
brick                        > Installing executable brick-readme-demo in /Users/roger/.stack/snapshots/aarch64-osx/4ffc2b29c12b3cae23c7a379a242de88e376f2e6d9da6f32712764d789c302af/9.2.7/bin
brick                        > Installing executable brick-edit-demo in /Users/roger/.stack/snapshots/aarch64-osx/4ffc2b29c12b3cae23c7a379a242de88e376f2e6d9da6f32712764d789c302af/9.2.7/bin
brick                        > Installing executable brick-list-vi-demo in /Users/roger/.stack/snapshots/aarch64-osx/4ffc2b29c12b3cae23c7a379a242de88e376f2e6d9da6f32712764d789c302af/9.2.7/bin
brick                        > Registering library for brick-1.4..
schedule-maker               > configure (lib + exe)
Configuring schedule-maker-0.1.0.0...
Completed 64 action(s).

Error: [S-7282]
       Stack failed to execute the build plan.

       While executing the build plan, Stack encountered the following errors:

       InvalidAbsFile "/Users/roger/.ghcup/ghc/9.2.5/lib/ghc-9.2.5/lib/../lib/aarch64-osx-ghc-9.2.5/rts-1.0.2/include/ghcversion.h"
```

Then, very confused, I checked ghcup, which claimed that 9.2.5 still existed. Confused, I tried to uninstall it again:

```
[ Info  ] Removing ghc-x.y.z symlinks
ghcup: /Users/roger/.ghcup/ghc/9.2.5/bin: getDirectoryContents:openDirStream: does not exist (No such file or directory)
```
So... I checked ~/.ghcup/ghc/9.2.5, and found it completely empty, but still there.

Still confused, removed the 9.2.5 empty directory. Now ghcup said that 9.2.5 wasn't installed, so I tried to install it. Now, after finishing the download, this error came up: 

```
[ Info  ] Merging file tree from "/Users/roger/.ghcup/tmp/ghcup-65ccd0008d530b97/Users/roger/.ghcup/ghc/9.2.5" to "/Users/roger/.ghcup/ghc/9.2.5"
Error: [GHCup-00080] Failed to merge file tree from /Users/roger/.ghcup/tmp/ghcup-65ccd0008d530b97/Users/roger/.ghcup/ghc/9.2.5 to /Users/roger/.ghcup/ghc/9.2.5
exception was: user error (mergeFileTree: DB file /Users/roger/.ghcup/db/ghc/9.2.5 already exists!)
...you may need to delete /Users/roger/.ghcup/ghc/9.2.5 manually. Make sure it's gone.
Also check the logs in ~/.ghcup/logs
```
I'm pretty clueless what would need to be done to fix this. I suppose the solution is to nuke ghcup and get a fresh install.

**Comment by hasufell** [comment]
That's a really depressing user experience...

However, I can't really reproduce it. I tried to follow the sequence indicated by @geekosaur but it didn't trigger it. I tried various other combinations... nothing.

There is one more possibility... I added a commit to the metadata that bumped the 'recommended' tag. That happened after HLS was bumped. So it's possible that when you started ghcup tui it didn't show that 1.10.0.0 is recommended yet. Then while the tui is in use for some time, it may refresh the metadata at some point (e.g. after 300 seconds... and this happens after a command executed successfully right before it sends you back to the TUI). Maybe it did refresh it and the tags changed and then somehow something got screwed up.

**Comment by geekosaur** [comment]
Actually I am quite sure the new HLS didn't show as recommended yet when I started, so that is a possibility.

**Comment by 0rphee** [comment]
I think something like this just happened to me again, I tried to uninstall ghc-9.2.8 through the TUI, but 'failed':
```
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[15:32:31] roger@mbair [~/Documents/Dev/haskell-proj/stan] git(main) 
❱❱❱ ghcup tui 
[ Info  ] downloading: https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-0.0.7.yaml as file /Users/roger/.ghcup/cache/ghcup-0.0.7.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Success
Press enter to continue

[ Info  ] Removing ghc-x.y.z symlinks
[ Info  ] Removing/rewiring ghc-x.y symlinks
[ Info  ] Removing files safely from: /Users/roger/.ghcup/ghc/9.2.8

ghcup: /Users/roger/.ghcup/ghc/9.2.8: removeDirectory: unsatisfied constraints (Directory not empty)
[cost 28.418s] [15:33:19] ghcup tui                                                                                                                                                            
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[15:33:22] roger@mbair [~/Documents/Dev/haskell-proj/stan] git(main) 
❱❱❱ /Users/roger/.ghcup/ghc/
[cost 0.024s] [15:33:30] /Users/roger/.ghcup/ghc/                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[15:33:38] roger@mbair [~/.ghcup/ghc] 
❱❱❱ ll -a 9.2.8            
total 16
drwxr-xr-x@ 3 roger  staff    96B Oct 20 15:33 .
drwxr-xr-x@ 6 roger  staff   192B Sep 18 21:27 ..
-rw-r--r--@ 1 roger  staff   6.0K Aug  7 14:16 .DS_Store
[cost 0.026s] [15:33:42] ll -a 9.2.8              
```
However, when opening the TUI, it says that 9.2.8 is still installed. I think the culprit of this issue, at least for macos, is the `DS_Store` file.

**Comment by hasufell** [comment]
Related: https://github.com/haskell/ghcup-hs/issues/797

**Comment by hasufell** [comment]
I believe this was a bug in brick that got fixed?
