### ISSUE TITLE
Incorrect message after removing HLS version

### ISSUE THREAD

**Issue by geekosaur** [haskell/ghcup-hs#817]
```
[ Info  ] Removing files safely from: /home/allbery/.local/share/ghcup/hls/1.9.0.0
[ Info  ] After removing GHC you might also want to clean up your cabal store at: ~/.cabal/store/ghc-1.9.0.0
Success
```
I don't think a message relevant to removing a GHC version belongs there?

**Comment by lsmor** [comment]
Actually this happens when you uninstall any tool from the TUI. The error is [here](https://github.com/haskell/ghcup-hs/blob/master/app/ghcup/BrickMain.hs#L566) I think I can push a fix
