### ISSUE TITLE
stack-building Agda with cpphs on Windows fails with ghcup-installed ghcs 9.2 and 9.4

### ISSUE THREAD

**Issue by andreasabel** [haskell/ghcup-hs#823]
I experience build failures of Agda in this combination
- Windows (local Windows 10, gha `windows-2022`)
- stack (latest)
- cpphs
- recently ghcup installed ghc (tested 9.4.5 9.4.4 9.4.3 9.2.7)

https://github.com/agda/agda/actions/runs/4827829386/jobs/8600964097#step:12:25
```
Agda       > C:\Users\RUNNER~1\AppData\Local\Temp\ghc1952_0\ghc_25.hscpp:1:7: error:
Agda       >     lexical error in pragma at character '1'
Agda       >   |
Agda       > 1 | #line 1 ".stack-work 
```

This issue goes away when one of:
- letting stack install ghc
- not using cpphs but default C preproc.
- using a non-recent ghc (I tried 8.8.4, ghcup-installed now, and 8.10.7, ghcup-installed 2022-08-14)

Original report here:
- https://github.com/commercialhaskell/stack/issues/6111

**Comment by hasufell** [comment]
I think we will have to involve GHC devs or cpphs devs here. I'm afraid I don't know too much about how cpphs interacts with GHC.

@bgamari @angerman @mpickering

**Comment by angerman** [comment]
I'm lost. What are the relevant `cpphs` versions? Does stack install a different `cpphs`?

I'm not terribly surprised that this would go away, if you use the stock that ghc assumes, and no one really saw the cpphs issue; I don't know how widespread that use is.

**Comment by andreasabel** [comment]
> I'm lost. What are the relevant `cpphs` versions? 

Latest, I suppose, which would be 1.20.9.1.

> Does stack install a different `cpphs`?

Maybe, but it should at least use the current `cpphs` in the testsuite for `cpphs`, which is in:
- https://github.com/hackage-trustees/malcolm-wallace-universe/pull/20

Is `cpphs` still a thing or should the Haskell community drop it?  I do so, after seeing the mess it causes on Windows:
- agda/agda#6600

**Comment by hasufell** [comment]
> Latest, I suppose, which would be 1.20.9.1.

You suppose? Did you actually verify?

**Comment by andreasabel** [comment]
> > Latest, I suppose, which would be 1.20.9.1.

Here is the hard evidence: 
- cabal: https://github.com/hackage-trustees/malcolm-wallace-universe/actions/runs/4858876155/jobs/8660803517#step:6:5
- stack: https://github.com/hackage-trustees/malcolm-wallace-universe/actions/runs/4858876154/jobs/8660803702#step:7:5

**Comment by andreasabel** [comment]
Update: I consider `cpphs` dead, so I don't care about this issue any longer.
