### ISSUE TITLE
How are "recommended" versions chosen?

### ISSUE THREAD

**Issue by Martinsos** [haskell/ghcup-hs#833]
When using GHCup, I usually stick to installing recommended versions of tools, and I also tell newcomers to Haskell to just install and set whatever is recommended.

However, I just got into a bit of trouble doing that, because it turned out that GHC 9.2.8, which is recommended, is not hls-powered. I unfortunately didn't see that, so it took me some time to realize why my editor is complaining that corresponding hls binary is missing. I also did not see warning message that ghcup tui printed, about such hls binary not existing. If I managed to miss all that, probably will some beginner also.

I wonder if it would be safer to mark only "hls-powered" GHC versions as recommended?

I also wonder why is such old cabal recommended -> 3.6.2.0, when there is 3.10.1.0 .

Looking forward to a bit of clarity on this, thanks!

**Comment by hasufell** [comment]
> However, I just got into a bit of trouble doing that, because it turned out that GHC 9.2.8, which is recommended, is not hls-powered.

Yes, I usually wait for that. @wz1000 provided a PR that bumped the recommended, so I was assuming a HLS bump release is in the pipeline? 

Going forward, I will not bump recommended until HLS has caught up.

> I also wonder why is such old cabal recommended -> 3.6.2.0, when there is 3.10.1.0 .

https://github.com/haskell/ghcup-metadata/issues/40

----

In general, this is already documented here: https://www.haskell.org/ghcup/install/#which-versions-get-installed

**Comment by ulysses4ever** [comment]
@hasufell note that most of the cabal issues you listed in https://github.com/haskell/ghcup-metadata/issues/40 are fixed by now.

**Comment by ulysses4ever** [comment]
From the remaining two open issues one (`pgm` stuff) is not considered a regression in 3.8 but upstream (GHC).

**Comment by hasufell** [comment]
wrt HLS: https://github.com/haskell/haskell-language-server/pull/3608

**Comment by hasufell** [comment]
> From the remaining two open issues one (`pgm` stuff) is not considered a regression in 3.8 but upstream (GHC).

there was another one where `cabal run` was broken on windows in some circumstance. I can't find it.

**Comment by ulysses4ever** [comment]
yes, this is https://github.com/haskell/cabal/issues/8841 it's been fixed on `master` already and in the process of being backported to the 3.10 branch, of which we expect to cut 3.10.2 Real Soon Now™

**Comment by Martinsos** [comment]
Thanks @hasufell , all makes sense! I missed that part in the docs, but it gives a good idea.
