### ISSUE TITLE
ghcup fails to install on FreeBSD-13.2 "Unable to find a download for the requested version/distro"

### ISSUE THREAD

**Issue by abnerseth** [haskell/ghcup-hs#834]
Hardware: Lenovo Thinkpad Yoga
Operating System: FreeBSD-13.2-RELEASE

`cat ~/.ghcup/logs/ghcup.log`
`Debug: Identified platform as: FreeBSD, 13.2-RELEASE`
`Debug: last access was 6.174976388s ago, cache interval is 300s`
`Debug: Decoding yaml at : /home/me/.ghcup/cache/ghcup-0.0.7.yaml`
`Error: [GHCup-00010] Unable to find a download for the requested version/distro.`
`Error: Also check the logs in /home/me/.hgcup/logs`

**Comment by abnerseth** [comment]
> What version did you request?

I used command:
`curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh`

**Comment by hasufell** [comment]
GHC has dropped explicit support for FreeBSD. New releases don't have upstream bindists. As such, I sometimes build GHC manually for FreeBSD, but that's cumbersome.

9.2.8 currently doesn't have a FreeBSD bindist and that's the version the script is trying to install.

You can direct it to install 9.2.7 instead:

```sh
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org |  BOOTSTRAP_HASKELL_GHC_VERSION=9.2.7 sh
```

Here's some info on FreeBSD revival:

- https://gitlab.haskell.org/ghc/ghc/-/issues/23124
- https://gitlab.haskell.org/groups/ghc/-/epics/5

Feel free to contact @arrowd if you want to push for better support.

**Comment by avysk** [comment]
Can I help somehow? I have FreeBSD 13.2 (both x64 and arm64) and reasonably good with computers. There are multiple unofficial bindists for FreeBSD but not 9.2.8 (shown by ghcup as "recommended") and not 9.6.2 ("latest"). I believe that all versions between are available.

**Comment by arrowd** [comment]
I have submitted 9.2.8 bindists yesterday: https://github.com/commercialhaskell/stackage-content/commit/d9b4f545da97711d19f5bff9becca45498986de6

**Comment by abnerseth** [comment]
Thank you!!!

**Comment by hasufell** [comment]
Well, ghcup doesn't use stacks metadata.
