### ISSUE TITLE
ghcup tui assumes alternate screens are available, looks awful

### ISSUE THREAD

**Issue by mauke** [haskell/ghcup-hs#837]
If the terminal doesn't support alternate screens (e.g. because I've turned off the feature because it makes `less -F` unusable), `ghcup tui` looks less than great.

The screenshots below show me downloading and installing HLS, and then exiting `ghcup`. The latter doesn't move the cursor to the bottom of the screen, so the shell prompt is kind of drawn within the carcass of the `ghcup` UI.

![Screenshot from 2023-06-10 16-01-37](https://github.com/haskell/ghcup-hs/assets/278465/d754b715-0225-4cff-9a07-f4697eda3d94)
![Screenshot from 2023-06-10 16-02-01](https://github.com/haskell/ghcup-hs/assets/278465/87b4382e-492c-4e46-9a4a-bc05d6fa19db)
![Screenshot from 2023-06-10 16-04-04](https://github.com/haskell/ghcup-hs/assets/278465/55c62c9e-cccc-4e92-b0fc-1070a7d366ac)
![Screenshot from 2023-06-10 16-04-36](https://github.com/haskell/ghcup-hs/assets/278465/fab46f1a-bb69-49a1-aa4a-364b3726dc52)

**Comment by hasufell** [comment]
Yep, that's true. The idea is to show the log inside the TUI proper in a "popup window", but I haven't gotten around doing that. It isn't trivial.

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-hs/issues/65
