### ISSUE TITLE
ghcup doesn't install on macos 13.4.1

### ISSUE THREAD

**Issue by GeorgeCo** [haskell/ghcup-hs#842]
ghcup doesn't install on macos 13.4.1
```
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

Welcome to Haskell!

This script can download and install the following binaries:
  * ghcup - The Haskell toolchain installer
  * ghc   - The Glasgow Haskell Compiler
  * cabal - The Cabal build tool for managing Haskell software
  * stack - A cross-platform program for developing Haskell projects (similar to cabal)
  * hls   - (optional) A language server for developers to integrate with their editor/IDE

ghcup installs only into the following directory,
which can be removed anytime:
  /Users/avie/.ghcup

Press ENTER to proceed or ctrl-c to abort.
Note that this script can be re-run at any given time.

-------------------------------------------------------------------------------

Detected bash shell on your system...
Do you want ghcup to automatically add the required PATH variable to "/Users/avie/.bashrc"?

[P] Yes, prepend  [A] Yes, append  [N] No  [?] Help (default is "P").


-------------------------------------------------------------------------------
Do you want to install haskell-language-server (HLS)?
HLS is a language-server that provides IDE-like functionality
and can integrate with different editors, such as Vim, Emacs, VS Code, Atom, ...
Also see https://haskell-language-server.readthedocs.io/en/stable/

[Y] Yes  [N] No  [?] Help (default is "N").


-------------------------------------------------------------------------------
Do you want to enable better integration of stack with GHCup?
This means that stack won't install its own GHC versions, but uses GHCup's.
For more information see:
  https://docs.haskellstack.org/en/stable/yaml_configuration/#ghc-installation-customisation-experimental
If you want to keep stacks vanilla behavior, answer 'No'.

[Y] Yes  [N] No  [?] Help (default is "Y").


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27.0M  100 27.0M    0     0  23.4M      0  0:00:01  0:00:01 --:--:-- 23.5M
[ Info  ] downloading: https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-0.0.7.yaml as file /Users/avie/.ghcup/cache/ghcup-0.0.7.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  263k  100  263k    0     0  1555k      0 --:--:-- --:--:-- --:--:-- 1566k
[ Info  ] Upgrading GHCup...
[ Warn  ] No GHCup update available

System requirements
  Note: On OS X, in the course of running ghcup you will be given a dialog box to install the command line tools. Accept and the requirements will be installed for you. You will then need to run the command again.
On Darwin M1 you might also need a working llvm installed (e.g. via brew) and have the toolchain exposed in PATH.
Press ENTER to proceed or ctrl-c to abort.
Installation may take a while.


[ Info  ] downloading: https://downloads.haskell.org/~ghc/9.2.8/ghc-9.2.8-x86_64-apple-darwin.tar.xz as file /Users/avie/.ghcup/cache/ghc-9.2.8-x86_64-apple-darwin.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  169M  100  169M    0     0  28.0M      0  0:00:06  0:00:06 --:--:-- 29.9M
[ Info  ] verifying digest of: ghc-9.2.8-x86_64-apple-darwin.tar.xz
[ Info  ] Unpacking: ghc-9.2.8-x86_64-apple-darwin.tar.xz to /Users/avie/.ghcup/tmp/ghcup-6d8bd913484b2b6f
[ Info  ] Installing GHC (this may take a while)






[ Error ] [ ]8;;https://errors.haskell.org/messages/GHCup-00841 \GHCup-00841 ]8;; \] Process "sh" with arguments ["./configure",
[ ...   ]                              "--prefix=/Users/avie/.ghcup/ghc/9.2.8",
[ ...   ]                              "--disable-ld-override"] failed with exit code 77.
[ Error ] Also check the logs in /Users/avie/.ghcup/logs
"ghcup --metadata-fetching-mode=Strict --cache install ghc recommended" failed!
bash-3.2$ 

```

**Comment by hasufell** [comment]
@angerman ideas?

**Comment by hasufell** [comment]
@GeorgeCo can you post the logs in `~/.ghcup/logs`?

**Comment by GeorgeCo** [comment]
uploaded 
[ghc-configure.log](https://github.com/haskell/ghcup-hs/files/11882476/ghc-configure.log)
[ghcup.log](https://github.com/haskell/ghcup-hs/files/11882477/ghcup.log)
In looking at the log files it seems clear that Xcode command line tools did not get installed. So I typed "xcode-select --install" and then reran the ghcup command and ghc got installed.

I thought I ran the command twice as your page requests but perhaps I didn't. But your page also says that the first invocation will install the command line tools but if so I'm surprised that "xcode-select --install" didn't say the tools were already installed.

**Comment by GeorgeCo** [comment]
I think ghcup should give a better error message in this case.

**Comment by hasufell** [comment]
> I think ghcup should give a better error message in this case.

It links you to https://errors.haskell.org/messages/GHCup-00841/

Which links you to https://www.haskell.org/ghcup/install/#system-requirements which clearly says to install command line tools

What else do you suggest?

**Comment by hasufell** [comment]
> Ideally the script would check for command line tools and install them if they are not there and then continue with the installation.

Never going to happen. It's against GHCup philosophy. See https://www.haskell.org/ghcup/about/#non-goals

> why not just put that error message in the output from the install command instead of having the user indirect through a link?

That's easier said than done. This error doesn't apply on linux or windows.

The configure script fails and it can do so for a bazillion reasons. You'd have to parse the log output and start guessing what's the actual error. There's no clean way to do this.

Usually the configure log is already self explanatory. 

> I am unaware of any language whose error messages indirect through a link

You are not aware of rust? https://doc.rust-lang.org/error_codes/error-index.html

This is an initiative by the Haskell Foundation. @david-christiansen may be able to say more about it.

> As we know that doesn't work on a MacOS machine that doesn't have command line tools installed.

The install script literally prints to the screen the following message and waits for you to press enter and acknowledge  that you understood:

```
On OS X, in the course of running ghcup you will be given a dialog
            box to install the command line tools. Accept and the requirements will
            be installed for you. You will then need to run the command again.

            On Darwin M1 you might also need a working llvm installed (e.g. via brew)
            and have the toolchain exposed in PATH.
```

Did you not see that message?

**Comment by GeorgeCo** [comment]
Sorry! Yes I agree that should be sufficient. I appreciate your patience. I have taken too much of your time already so you don't need to read the rest of this.

As I wrote above:

```
I thought I ran the command twice as your page requests but perhaps I didn't. But your page also says that the first invocation will install the command line tools but if so I'm surprised that "xcode-select --install" didn't say the tools were already installed.
```

I tried xcode-select --install again and it does say the Command Line Tools are installed. It is possible that the first invocation did not install them but if that is the case somebody else will file a bug and it can be fixed then. I don't think it is worth testing for this possibility.

**Comment by hasufell** [comment]
@GeorgeCo for example, we could document the issue with xcode more prominently here: https://github.com/haskellfoundation/error-message-index/blob/main/message-index/messages/GHCup-00841/index.md

This will then show up here: https://errors.haskell.org/messages/GHCup-00841/

**Comment by GeorgeCo** [comment]
@hasufell. Thanks for your quick, helpful and patient responses. All my points are very minor and it certainly makes sense to rely on others to implement any of them. Thanks again!

**Comment by chreekat** [comment]
Relatedly, GHC CI itself just broke because (we think?) XCode silently updated itself, bringing in a new warning that doesn't even matter for us.
