### ISSUE TITLE
[Question] How to export the result of 'ghcup run' to PATH

### ISSUE THREAD

**Issue by July541** [haskell/ghcup-hs#853]
The usage for 'ghcup run' says it can 'Adds the given tools to a dedicated bin/directory and adds them to PATH'. But I don't find any option to do the 'add to PATH' step.

**Comment by hasufell** [comment]
E.g.:

```sh
export PATH="$(ghcup run --ghc latest --hls latest --cabal latest --stack latest):$PATH"
```

**Comment by July541** [comment]
Is it possible to add a new option like '--export' to do the export directly?

**Comment by hasufell** [comment]
That is not possible.

See https://stackoverflow.com/a/23183187

**Comment by July541** [comment]
Oh, I forgot it's not shell😅
