### ISSUE TITLE
Audit GHCup download practices, e.g. through the Haskell Security Response team

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#858]
This came to my mind when reading #836

I'm not sure if this is in your scope, but I'd appreciate if you or someone else reviews download practices, checksum and gpg strategies and so on.

Relevant pieces:

* checksum checking of metadata:
  * https://github.com/haskell/ghcup-metadata
    * all downloads have checksums, e.g. https://github.com/haskell/ghcup-metadata/blob/0759634d3ca22ccdda67c2fccf89a88d1e9a5655/ghcup-0.0.7.yaml#L2078-L2082
    * the repository also contains gpg signatures for all files, e.g. https://github.com/haskell/ghcup-metadata/blob/develop/ghcup-0.0.7.yaml.sig
  * https://github.com/haskell/ghcup-hs/blob/d143daeb9a021ac7bd9c1fc1999a057ebc673547/lib/GHCup/Download.hs#L690-L708
  * https://github.com/haskell/ghcup-hs/blob/d143daeb9a021ac7bd9c1fc1999a057ebc673547/lib/GHCup/Download.hs#L428
  * https://github.com/haskell/ghcup-hs/blob/d143daeb9a021ac7bd9c1fc1999a057ebc673547/lib/GHCup/Download.hs#L358
* optional gpg verification:
  * https://www.haskell.org/ghcup/guide/#gpg-verification
  * https://github.com/haskell/ghcup-hs/blob/d143daeb9a021ac7bd9c1fc1999a057ebc673547/lib/GHCup/Download.hs#L418-L424
* bootstrapping scripts (naturally the most vulnerable)
  * linux: https://github.com/haskell/ghcup-hs/blob/master/scripts/bootstrap/bootstrap-haskell
  * windows: https://github.com/haskell/ghcup-hs/blob/master/scripts/bootstrap/bootstrap-haskell.ps1
    * note that msys2 installation is only carried out here, not through the main ghcup program (and as such is not part of ghcup metadata)

@david-christiansen @frasertweedale @chreekat

**Comment by frasertweedale** [comment]
@hasufell thanks.  It's not formally in SRT scope of work but given the critical role of GHCup I think the SRT can probably take a look.  I'll bring it up at the next meeting.

Informally and in brief, the approach seems sound, up to:

- ghcup performs TLS certificate validation (GitHub, `get-ghcup.haskell.org`, `downloads.haskell.org`, ...?)
- ghcup checks the digests
- proper management of the *ghcup-metadata* repository
- proper management of the bootstrap script at `get-ghcup.haskell.org` and relevant content at `downloads.haskell.org`
  - This may be the weakest point.
- sound TLS key management for `get-ghcup.haskell.org`, `downloads.haskell.org`

The OpenPGP signature on the metadata provides an additional layer of validation, up to proper key management, but I think the scheme is sufficient without it, if the points above are satisfied.

In relation to msys2, I think using a verified/tested copy of the content, hosted by us, as suggested in #836, is prudent.

**Comment by hasufell** [comment]
> ghcup performs TLS certificate validation

Yes, through either `curl` or `wget`. We specifically avoid haskell-tls, because it's not audited and I don't trust Haskell to do correct crypto.

**Comment by frasertweedale** [comment]
@hasufell, SRT will have a closer look at GHCUp security model in the coming weeks.

**Comment by hasufell** [comment]
The use of `curl` and `wget` binary has seen *some* controversy: we're basically relying on

* the distribution to track and fix CVEs
* the end users to keep their system up to date through their package manager

In my view, these are good assumptions to make. Others disagree and would rather control the entire environment.
