### ISSUE TITLE
Windows bootstrapping settings seem to produce errors when linking

### ISSUE THREAD

**Issue by jasagredo** [haskell/ghcup-hs#859]
# Summary
I've been trying to compile `basement` in Windows with MSYS2 and MinGW installed via GHCup, however, unless I comment out the `extra-lib-dirs` and `extra-include-dirs`, compilation fails. Are these arguments actually required?

https://github.com/haskell/ghcup-hs/blob/d143daeb9a021ac7bd9c1fc1999a057ebc673547/scripts/bootstrap/bootstrap-haskell#L594

# Explanation and details

I will discuss details here which might be a bit too verbose or be an issue for the GHC tracker, but in the end it is changing those two lines what results in a successful compilation.

The current versions on my system (Windows 10) are as follows:
```
➜  uname
MINGW64_NT-10.0-22621
➜  which ghc; ghc --version; which cabal; cabal --version
/c/ghcup/bin/ghc
The Glorious Glasgow Haskell Compilation System, version 9.2.8
/c/ghcup/bin/cabal
cabal-install version 3.10.1.0
compiled using version 3.10.1.0 of the Cabal library
```

My `/c/cabal/config` options from that line of code are as follows:
```
extra-prog-path: C:\ghcup\bin,
                 C:\cabal\bin,
                 C:\ghcup\msys64\mingw64\bin,
                 C:\ghcup\msys64\usr\bin
extra-include-dirs: C:\ghcup\msys64\mingw64\include
extra-lib-dirs: C:\ghcup\msys64\mingw64\lib
```

If there is any other file or variable you would like to see just let me know.

When I try to build `basement` I get the following error:
```
➜  foundation git:(master) ✗ cabal build basement
Resolving dependencies...
Build profile: -w ghc-9.2.8 -O1
In order, the following will be built (use -v for more details):
 - basement-0.0.16 (lib) (first run)
Configuring library for basement-0.0.16..
Preprocessing library for basement-0.0.16..
linking C:\Users\Javier\foundation\dist-newstyle\build\x86_64-windows\ghc-9.2.8\basement-0.0.16\build\Basement\Terminal\Size_hsc_make.o failed (exit code 1)
rsp file was: "C:\\Users\\Javier\\foundation\\dist-newstyle\\build\\x86_64-windows\\ghc-9.2.8\\basement-0.0.16\\build\\Basement\\Terminal\\hscAD33.rsp"
command was: C:\ghcup\ghc\9.2.8\lib\../mingw/bin\gcc.exe C:\Users\Javier\foundation\dist-newstyle\build\x86_64-windows\ghc-9.2.8\basement-0.0.16\build\Basement\Terminal\Size_hsc_make.o C:\Users\Javier\foundation\dist-newstyle\build\x86_64-windows\ghc-9.2.8\basement-0.0.16\build\Basement\Terminal\Size_hsc_utils.o -o C:\Users\Javier\foundation\dist-newstyle\build\x86_64-windows\ghc-9.2.8\basement-0.0.16\build\Basement\Terminal\Size_hsc_make.exe -LC:\ghcup\msys64\mingw64\lib -LC:\ghcup\ghc\9.2.8\lib\x86_64-windows-ghc-9.2.8\Win32-2.12.0.1 -luser32 -lgdi32 -lwinmm -ladvapi32 -lshell32 -lshfolder -lshlwapi -lmsimg32 -limm32 -LC:\ghcup\ghc\9.2.8\lib\x86_64-windows-ghc-9.2.8\filepath-1.4.2.2 -LC:\ghcup\ghc\9.2.8\lib\x86_64-windows-ghc-9.2.8\base-4.16.4.0 -lwsock32 -luser32 -lshell32 -lmsvcrt -lmingw32 -lmingwex -lws2_32 -lshlwapi -lole32 -lrpcrt4 -lntdll -LC:\ghcup\ghc\9.2.8\lib\x86_64-windows-ghc-9.2.8\ghc-bignum-1.2 -LC:\ghcup\ghc\9.2.8\lib\x86_64-windows-ghc-9.2.8\ghc-prim-0.8.0 -luser32 -lmingw32 -lmingwex -LC:\ghcup\ghc\9.2.8\lib\x86_64-windows-ghc-9.2.8\rts-1.0.2 -lm -lwsock32 -lgdi32 -lwinmm -ldbghelp -lpsapi -lmingwex
error: C://ghcup//ghc//9.2.8//mingw//bin/ld.exe: C://ghcup//ghc//9.2.8//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_app_type[.refptr.mingw_app_type]+0x0): undefined reference to `mingw_app_type'
C://ghcup//ghc//9.2.8//mingw//bin/ld.exe: C://ghcup//ghc//9.2.8//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initcharmax[.refptr.mingw_initcharmax]+0x0): undefined reference to `mingw_initcharmax'
C://ghcup//ghc//9.2.8//mingw//bin/ld.exe: C://ghcup//ghc//9.2.8//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initltssuo_force[.refptr.mingw_initltssuo_force]+0x0): undefined reference to `mingw_initltssuo_force'
C://ghcup//ghc//9.2.8//mingw//bin/ld.exe: C://ghcup//ghc//9.2.8//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initltsdyn_force[.refptr.mingw_initltsdyn_force]+0x0): undefined reference to `mingw_initltsdyn_force'
C://ghcup//ghc//9.2.8//mingw//bin/ld.exe: C://ghcup//ghc//9.2.8//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initltsdrot_force[.refptr.mingw_initltsdrot_force]+0x0): undefined reference to `mingw_initltsdrot_force'
collect2.exe: error: ld returned 1 exit status

Error: cabal-3.10.1.0.exe: Failed to build basement-0.0.16.
```

I've been trying to find out what was going on with those undefined symbols, without much luck, only to find [this comment by Ryan](https://gitlab.haskell.org/ghc/ghc/-/issues/21111#note_418314), which prompted me to comment out those lines, which lead to a successful compilation. 

```
➜  foundation git:(master) ✗ cabal build basement
Build profile: -w ghc-9.2.8 -O1
In order, the following will be built (use -v for more details):
 - basement-0.0.16 (lib) (configuration changed)
Configuring library for basement-0.0.16..
Preprocessing library for basement-0.0.16..
Building library for basement-0.0.16..
[ 1 of 84] Compiling Basement.Compat.Bifunctor ( Basement\Compat\Bifunctor.hs, C:\\Users\Javier\foundation\dist-newstyle\build\x86_64-windows\ghc-9.2.8\basement-0.0.16\build\Basement\Compat\Bifunctor.o )
...
➜  foundation git:(master) ✗ cabal build basement
Up to date
```

**Comment by hasufell** [comment]
That's odd, because https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7611 indicates the GHC fix made it into the 9.2.x branch.

**Comment by hasufell** [comment]
Can you try ghc 9.4.5 instead?

**Comment by jasagredo** [comment]
Indeed `cabal build basement` succeeds for GHC 9.4.5 either with or without those arguments.

**Comment by hasufell** [comment]
So the issues are gone with 9.4.5, is that correct? Because that's expected.

**Comment by jasagredo** [comment]
Yeah, let me summarize it here.

## Haskell-only library (https://hackage.haskell.org/package/basement)

| | 9.2.8 | 9.4.5 |
|-|-|-|
| with extra dirs | N | Y |
| without extra dirs | Y | Y |

## Library with foreign dependency (https://github.com/input-output-hk/haskell-lmdb)

| | 9.2.8 | 9.4.5 |
|-|-|-|
| with extra dirs | N | Y (with gcc warnings) |
| without extra dirs | N | Y (with gcc warnings) |

**Comment by hasufell** [comment]
Got it... so going forwards, we'll likely make 9.4.5 (or 9.4.6 which is not released yet) the new 'recommended' GHC version in GHCup.

Further, we're trying to gather some documentation for users on how to survive this msys2 experience. See:

* https://gitlab.haskell.org/ghc/ghc/-/issues/21491
* https://gitlab.haskell.org/ghc/ghc/-/wikis/surviving-windows

**Comment by hasufell** [comment]
> Should [this line](https://github.com/actions/runner-images/blob/main/images/win/scripts/Installers/Install-Haskell.ps1#L13) instead provide $false to [switch]$NoAdjustCabalConfig,? Otherwise I have to do this at the beginning of my GH workflow:

I believe we omitted that on purpose, because of various issues. People who need msys2 packages will have to do some work, but the default seems safer.

**Comment by jasagredo** [comment]
I was able to build a Windows lib+binary that depended on msys packages without having to use these extra directories. The solution can be seen [here](https://github.com/input-output-hk/actions/pull/4/files#diff-b3c20bb50996c2d25c382a4160f8ab08355fede07718cd6608d92963705787bdR38-R46). In general it is a problem of `pkg-config` in MSYS2.
