### ISSUE TITLE
Req: commandline flag to run without curses

### ISSUE THREAD

**Issue by pepa65** [haskell/ghcup-hs#863]
It would greatly enhance compatibility if `ghcup` could be used without any libtinfo, just on a plain terminal.

**Comment by hasufell** [comment]
We're using brick, which uses vty under the hood. This is unlikely to change, although there's a prototype based on ansi-terminal: https://github.com/haskell/ghcup-hs/pull/702

But I'm unlikely to pursue that further. Brick will have windows support soon.

**Comment by pepa65** [comment]
I am on Ubuntu 16.04.7 LTS (GNU/Linux 3.4.112-sun7i armv7l), and there are no libtinfo version 5 binaries around anymore.

**Comment by hasufell** [comment]
I think you're referring to the binary being dynamically linked against libtinfo. That's a distribution issue.

We would need alpine armv7 bindists to build a fully static ghcup binary there. This is unlikely to happen, but there are plans to do that for alpine aarch64: https://gitlab.haskell.org/ghc/ghc/-/issues/23482

**Comment by pepa65** [comment]
But do you absolutely need to link against libtinfo? Isn't it nice to have the option to just have plain terminal output without mandating curses?
