### ISSUE TITLE
Windows Suggestion: Alter System Environment Variables / Add ways to pass commands to Msys a la Stack

### ISSUE THREAD

**Issue by liamzee** [haskell/ghcup-hs#872]
I'm currently writing a tutorial on how to get a Monomer app up in Windows, but a huge headache I've discovered is the need to set system environment variables, and the target audience may not be happy with either local optimum (set system environment variables through Windows interface, or set system environment variables temporarily in command prompt or powershell).

Is there a way to get ghcup to populate the following in system environment variables:

$env:PATH="C:\ghcup\msys64\mingw64\bin; $env:PATH"
$env:PKG_CONFIG_PATH="C:\ghcup\msys64\mingw64\lib; $env:PKG_CONFIG_PATH"
$env:XDG_DATA_DIRS="C:\ghcup\msys64\mingw64\lib\pkgconfig"; $env:XDG_DATA_DIRS"

This is what's needed for monomer; gi-gtk I think needs a separate set of hacks. You might need administrator privileges to set this permanently or per user.

***

Another thing, might you be interested in adding ways to call the msys cabal is going to use? For libraries that depend on pkgconfig or C packages, it would be more ergonomic (and less threatening) to go through GHCup instead of manually opening mingw64 or the relevant application.

**Comment by liamzee** [comment]
I was told -m exists, and to get access to the relevant mingw module, I should be using ghcup -m mintty. Might these features be more prominently presented in Windows installations?

**Comment by liamzee** [comment]
I checked, apparently there's no standard way to configure GHCup path on Windows right now.

**Comment by hasufell** [comment]
- putting msys2 things in PATH permanently is discouraged and can break other applications
- ghcup configures cabal already to know about msys libraries and include dirs, so there shouldn't be a need to start a full msys2 shell to build monomer. Everything else is a bug.
- you can use `ghcup run --mingw-path -- some-binary` and it will add msys2 bin dirs to PATH for the invocation

**Comment by hasufell** [comment]
I don't know. I don't have a reproducer.

**Comment by liamzee** [comment]
Monomer right now is not in good shape, at least with my system, due to apparent issues with freetype (which may also exist on Linux, and it's apparently freetype / harfbuzz's fault).

But iirc, if you follow the instructions, use the right workarounds, and try to install the lib, it'll work.

Gi-GTK, on the other hand, explicitly recommends temporarily setting path variables in cmd.exe (I also got the instructions translated to power shell).

**Comment by hasufell** [comment]
If you don't provide a clear step by step reproducer, I cannot help.

**Comment by liamzee** [comment]
Let's close this then; the issues underlying monomer do not have that much to do with GHCup. As for GI-GTK, there are clear workarounds, to which you've contributed. Thanks for all the hard work.
