### ISSUE TITLE
Problem when downloading GHCup installer

### ISSUE THREAD

**Issue by RabidClover** [haskell/ghcup-hs#876]
When I use the code
 `Set-ExecutionPolicy Bypass -Scope Process -Force;[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; try { Invoke-Command -ScriptBlock ([ScriptBlock]::Create((Invoke-WebRequest https://www.haskell.org/ghcup/sh/bootstrap-haskell.ps1 -UseBasicParsing))) -ArgumentList $true } catch { Write-Error $_ }` 
 provided from the website to download haskell, it came out an error attached below
<img width="651" alt="image" src="https://github.com/haskell/ghcup-hs/assets/126318430/fe19ed17-eb90-45c1-9a85-b1a86bf71311">
Is there any way to solve this?
p.s.: I have disabled my antivirus software, still couldn't work

**Comment by hasufell** [comment]
https://www.haskell.org/ghcup/install/#windows_1

**Comment by hasufell** [comment]
Will close in 1 week if no further input.
