### ISSUE TITLE
haskel wont properly run

### ISSUE THREAD

**Issue by 679184** [haskell/ghcup-hs#878]
PS C:\Users\Tord> ghci
GHCi, version 9.2.8: https://www.haskell.org/ghc/  :? for help
<command line>: user specified .o/.so/.DLL could not be loaded (addDLL: pthread or dependencies not loaded. (Win32 error 5))
Whilst trying to load:  (dynamic) pthread
Additional directories searched:   C://ghcup//ghc//9.2.8//mingw//bin/
   C://ghcup//ghc//9.2.8//mingw//bin/../lib/
   C://ghcup//ghc//9.2.8//mingw//bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/
   C://ghcup//ghc//9.2.8//mingw//bin/../x86_64-w64-mingw32/lib/
   C:/ghcup/ghc/9.2.8/mingw/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/
   C:/ghcup/ghc/9.2.8/mingw/bin/../lib/gcc/
   C:/ghcup/ghc/9.2.8/mingw/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/lib/../lib/
   C:/ghcup/ghc/9.2.8/mingw/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib/
   C:/ghcup/ghc/9.2.8/mingw/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/lib/
   C:/ghcup/ghc/9.2.8/mingw/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../
   C:\WINDOWS\system32
PS C:\Users\Tord>

i get this error message after trying to run the comand "ghci" to open haskell

**Comment by hasufell** [comment]
Please report this at the GHC issue tracker: https://ghc.gitlab.haskell.org/

**Comment by chreekat** [comment]
+1 to opening a ticket. The canonical url is https://gitlab.haskell.org/ghc/ghc/ . @679184, if you don't already have an account there, let me know when you've created one and I can approve it.

**Comment by 679184** [comment]
i have made an account with username tord if you could approve

**Comment by hasufell** [comment]
Approved
