### ISSUE TITLE
Error installing ghcup on D: in a windows 10 environment

### ISSUE THREAD

**Issue by Piskator** [haskell/ghcup-hs#884]
I try to install ghc and stack using ghcup on a windows 10 computer on the D:drive , with both ghcup and msys2 destined to be on the D: drive using the instructions at https://www.haskell.org/ghcup/install/#windows_1 , i get the following error message however

```
PS D:\ghcup\bin> ghcup install ghc --set recommended
[ Info  ] downloading: https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-0.0.7.yaml as file D:ghcup\cache\ghcup-0.0.7.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  292k  100  292k    0     0   442k      0 --:--:-- --:--:-- --:--:--  444k
[ Info  ] downloading: https://downloads.haskell.org/~ghcup/shimgen/shim-2.exe as file D:ghcup\cache\gs.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  113k  100  113k    0     0   883k      0 --:--:-- --:--:-- --:--:--  904k
[ Info  ] verifying digest of: gs.exe
[ Info  ] downloading: https://downloads.haskell.org/~ghc/9.2.8/ghc-9.2.8-x86_64-unknown-mingw32.tar.xz as file D:ghcup\tmp\ghcup-b20254bb9508cca9\ghc-9.2.8-x86_64-unknown-mingw32.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  482M  100  482M    0     0  34.0M      0  0:00:14  0:00:14 --:--:-- 34.3M
[ Info  ] verifying digest of: ghc-9.2.8-x86_64-unknown-mingw32.tar.xz
[ Info  ] Unpacking: ghc-9.2.8-x86_64-unknown-mingw32.tar.xz to D:ghcup\tmp\ghcup-45bf0214a3f5f637
[ Error ] [GHCup-07320] Both installation and setting the tool failed. Install error was: Tar directory does not exist: ghc-9.2.8-x86_64-unknown-mingw32
[ ...   ] Set error was: The version 9.2.8 of the tool ghc is not installed.
[ Error ] Also check the logs in D:ghcup\logs```

**Comment by hasufell** [comment]
Use `D:\\`.

**Comment by Piskator** [comment]
That worked, but now if I go to a project on my D: drive, and  `stack build` it starts installing msys2 on the C-drive in the `C:\Users\myuser\AppData\Local\Programs\stack\x86_64-windows` folder and not the one I specified during the `ghcup` installation. How can I avoid this, and what are the next steps from the  https://www.haskell.org/ghcup/install/#windows_1  when trying to use another drive for global and local project environments?

**Comment by hasufell** [comment]
To instruct stack to use the ghcup provided GHC, read up on:

- https://docs.haskellstack.org/en/stable/yaml_configuration/#ghc-installation-customisation
- https://www.haskell.org/ghcup/guide/#strategy-2-stack-hooks-new-recommended

To make it use ghcup's msys2, you have to configure various stack variables: `skip-msys2`, `extra-path`, `extra-include-dirs`, `extra-lib-dirs`

Read up on them in the stack docs: https://docs.haskellstack.org/en/stable/yaml_configuration/#skip-msys
