### ISSUE TITLE
GHCup prints wrong cabal store path after removing GHC

### ISSUE THREAD

**Issue by openingnow** [haskell/ghcup-hs#888]
https://github.com/haskell/ghcup-hs/blob/371eda962f713fe483616310291004a82e5b029d/app/ghcup/GHCup/OptParse/Common.hs#L827

The path is `~/.local/state/cabal/store` since cabal 3.10.

**Comment by chreekat** [comment]
Nice catch! Would you like to try fixing it?

**Comment by openingnow** [comment]
@chreekat I guess there are 2 ways to fix this.
1. Simply change the hardcoded string to `~/.cabal/store or ~/.local/state/cabal/store` (and then finally change to the latter one when cabal<=3.8 is no longer supported)
1. Show different paths depending on the activated cabal version
If the second one is needed, it's beyond my capabilities.

**Comment by hasufell** [comment]
My suggestion would be to inform the user about both PATHs. Let's not get into the business of guessing user config and the cabal version they use. It's hard.

**Comment by openingnow** [comment]
resolved #890

**Comment by openingnow** [comment]
resolved #890
