### ISSUE TITLE
Haskell installation in Windows 10

### ISSUE THREAD

**Issue by wangmargaret** [haskell/ghcup-hs#894]
While install haskell via the guidline from https://www.haskell.org/ghcup/#, below errors while MinGW x64:

[\\ Error ] [GHCup-05841] Download failed: Process "wget" with arguments ["-q", "-S", "-O",
[ ...   ]                                                 "C:/ghcup\\cache\\ghcup-0.0.7.yaml.tmp",
[ ...   ]                                                 "https://raw.githubusercontent.com/haskell
/ghcup-metadata/master/ghcup-0.0.7.yaml"] failed with exit code 4.

**Comment by hasufell** [comment]
Is wget installed?

**Comment by wangmargaret** [comment]
Not yet, Hasufell.

**Comment by wangmargaret** [comment]
Has someone tried the manuall install Haskell?

**Comment by wangmargaret** [comment]
> Is wget installed?

Are there any way we can install wget? Thanks for your help...

**Comment by hasufell** [comment]
> > Is wget installed?
> 
> Are there any way we can install wget? Thanks for your help...

https://www.msys2.org/docs/package-management/
