### ISSUE TITLE
Resulting GHC is broken on macOS if Xcode is installed but the "Command Line Tools" aren't

### ISSUE THREAD

**Issue by tbodt** [haskell/ghcup-hs#901]
xcode-select --install installs a stripped down subset of Xcode's SDK in /Library/Developer/CommandLineTools. However, this should not be necessary if the full Xcode is installed. ghcup seems to not understand this and hardcodes the /Library/Developer/CommandLineTools path, resulting in this error from any ghc build:

```
ld: warning: directory not found for option '-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib'
Undefined symbols for architecture arm64:
  "_ffi_call", referenced from:
      _interpretBCO in libHSrts-1.0.2.a(Interpreter.o)
  "_ffi_closure_free", referenced from:
      _freeHaskellFunctionPtr in libHSrts-1.0.2.a(LibffiAdjustor.o)
ld: symbol(s) not found for architecture arm64
```

**Comment by hasufell** [comment]
I'm not sure how this is an issue with GHCup. Can you report this on GHC issue tracker?

> ghcup seems to not understand this and hardcodes the /Library/Developer/CommandLineTools path

No it does not.

**Comment by tbodt** [comment]
Weird. Where might this bad link arg be coming vrom then?

**Comment by hasufell** [comment]
> Weird. Where might this bad link arg be coming vrom then?

GHC?

**Comment by bgamari** [comment]
@tbodt, have you opened a GHC ticket for this?

**Comment by tbodt** [comment]
Haven't gotten around to it
