### ISSUE TITLE
The installation docs for Ubuntu need new instructions for Ubuntu 23.10

### ISSUE THREAD

**Issue by ppp7032** [haskell/ghcup-hs#902]
The [instructions](https://www.haskell.org/ghcup/install/) for installing GHCup dependencies on Ubuntu versions >= 20.10 do not work on Ubuntu 23.10. New installation instructions are needed. The relevant output from attempting the installation of the >= 20.10 dependencies on 23.10 is shown below:

```
Note, selecting 'libffi8' instead of 'libffi8ubuntu1'
E: Unable to locate package libncurses5
E: Unable to locate package libtinfo5
```

**Comment by hasufell** [comment]
Well, you need ncurses5 for older GHCs. This is a f*ckup of debian:

* https://answers.launchpad.net/ubuntu/+source/ncurses/+question/707838
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025964

They don't seem to care about binary compatibility.
