### ISSUE TITLE
Fails to build on windows

### ISSUE THREAD

**Issue by ShrykeWindgrace** [haskell/ghcup-hs#908]
### Symptoms
I tried this incantation https://github.com/jtdaugherty/vty/issues/260#issuecomment-1774848606 to no avail:
```console
PS> git branch
* (HEAD detached at v0.1.19.4)
  master
PS> cabal --project-file=cabal.project.release build -w ghc-9.2.8
<skip a lot of logs>
Failed to build network-3.1.4.0. The failure occurred during the configure
step.
Build log (
E:\nosave\Projects\Haskell\ghcup\cabal\logs\ghc-9.2.8\network-3.1.4.0-2e31fdac639cce47b661c4e59eacfd57d88dc7b2.log
):
Configuring network-3.1.4.0...
/E/nosave/Projects/Haskell/upstream/ghcup-hs/dist-newstyle/tmp/src-26766/network-3.1.4.0/configure: /E/nosave/Projects/Haskell/upstream/ghcup-hs/dist-newstyle/tmp/src-26766/network-3.1.4.0/configure.sh: No such file or directory
Error: cabal-3.10.1.0.exe: Failed to build network-3.1.4.0 (which is required
by exe:ghcup from ghcup-0.1.19.4). See the build log above for details.
```
All tools are installed via `ghcup`, the machine runs under a Win10, shell is `pwsh-7.3.8`.

### Investigation
`/E/nosave/` are not valid windows paths, I'd wager a guess that `cabal` and its minions are assuming some sort of `msys/mingw` environment.

**Comment by hasufell** [comment]
Sounds like you don't have a correct toolchain installed with msys2 and cabal configured to know the location. 

How did you install GHC?

**Comment by ShrykeWindgrace** [comment]
Via `ghcup install ghc 9.2.8`. I have
```
PS> get-command cabal

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     cabal.exe                                          0.0.0.0    E:\nosave\Projects\Haskell\ghcup\ghcup\bin\cabal.exe
PS>  cabal --version
cabal-install version 3.10.1.0
compiled using version 3.10.1.0 of the Cabal library
PS> get-command ghc-9.2.8

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ghc-9.2.8.exe                                      0.0.0.0    E:\nosave\Projects\Haskell\ghcup\ghcup\bin\ghc-9.2.8.exe
```

**Comment by chhackett** [comment]
Not sure if I should open a separate issue or not, but when I was building on Windows I see a different error:
Failed to build libarchive-3.0.4.2.
Build log (
C:\cabal\logs\ghc-9.4.7\libarchive-3.0.4.2-e3fd3fb934b218c0e216edd7965e8deee92005d4.log
):
Preprocessing library for libarchive-3.0.4.2..
c2hs.exe: C header contains errors:

C:/ghcup/ghc/9.4.7/mingw/lib/clang/14.0.6/include/ia32intrin.h:222: (column 29) [ERROR]  >>> Syntax error !
  The symbol `unsigned' does not fit here.

 C:\\dev\\projects\\ghcup-hs\\dist-newstyle\\tmp\\src-18337\\libarchive-3.0.4.2\\dist\\setup\\setup.exe
Configuring libarchive-3.0.4.2...
Error: cabal-3.8.1.0.exe: Failed to build libarchive-3.0.4.2 (which is
required by exe:ghcup from ghcup-0.1.19.5). See the build log above for
details.

I thought @hasufell mentioned this error somewhere also, but I can't find it now. It does appear to be a bug in the c2hs tool, so would have to be fixed there.

**Comment by ShrykeWindgrace** [comment]
Yes, I saw `libarchive` problems, too. I think I made some progress by setting the flag `system-libarchive: false`, but then I got some other errors with multiply defined symbols.

**Comment by hasufell** [comment]
@chhackett that's already reported here: https://github.com/vmchale/libarchive/pull/34

**Comment by hasufell** [comment]
https://github.com/vmchale/libarchive/pull/35
