### ISSUE TITLE
When missing permission to write to Desktop on Windows, installation fails.

### ISSUE THREAD

**Issue by barnabwhy** [haskell/ghcup-hs#914]
When installing on Windows, the installation fails when attempting to create files on the desktop if the user has disabled permissions to write to the Desktop folder.

![image](https://github.com/haskell/ghcup-hs/assets/22575741/9cf9fc68-e4d3-4907-a4ce-471d77d8fb1d)

**Comment by hasufell** [comment]
I think what we should really do here is ask if the user wants those shortcuts created on their desktop. If yes, then we expect it to be writable. If not, we just  skip.

Is that an appropriate solution?

**Comment by barnabwhy** [comment]
> I think what we should really do here is ask if the user wants those shortcuts created on their desktop. If yes, then we expect it to be writable. If not, we just skip.
> 
> Is that an appropriate solution?

Seems appropriate to me, after all the desktop is writable by default and anyone who set it to not be likely will press no for shortcuts

**Comment by hasufell** [comment]
This should be fixed now.
