### ISSUE TITLE
Unexpected behavior when setting (S-key) the ghcup version in tui

### ISSUE THREAD

**Issue by konnik** [haskell/ghcup-hs#923]
I mostly use ghcup tui for managing the different tools. Today I wanted to upgrade from 0.1.19.4 to the latest ghcup and started the tui with `ghcup tui`.  Both the current installed ghcup version and the new version is listed.

I selected the latest version 0.1.20.0 and pressed the key S.

## Actual behavior:

Console shows:

```
Success
Press enter to continue
```

After the pressing enter, the current version is still installed and the latest version is listed as not installed.

## Expected behavior:

```
This Version of ghcup you are trying to set is not installed.
Would you like to install it first? [Y/N]: 
Y

Success
Press enter to continue
```

After the pressing enter, the current version is not listed and the new version is listed as installed.

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-hs/pull/926/commits/6047614a16f04ba0d5f1d50046538d0ae5f7416a
