### ISSUE TITLE
SSL Problem

### ISSUE THREAD

**Issue by RMartinF** [haskell/ghcup-hs#929]
I'm trying to install haskell on Windows 11 as recommended on site https://www.haskell.org/ghcup/#, but installation results in an error:

curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - Die Sperrfunktion konnte keine Sperrprüfung für das Zertifikat durchführen.
Set-ExecutionPolicy Bypass -Scope Process -Force;[System.Net.ServicePointManager]::SecurityProtocol =
[System.Net.ServicePointManager]::SecurityProtocol -bor 3072; try { Invoke-Command -ScriptBlock
([ScriptBlock]::Create((Invoke-WebRequest https://www.haskell.org/ghcup/sh/bootstrap-haskell.ps1 -UseBasicParsing)))
-ArgumentList $true } catch { Write-Error $_ } : Exec: Error executing command curl.exe with arguments '-o
C:\Users\Martin\AppData\Local\Temp\\msys2-base-x86_64-20221216.sfx.exe
https://downloads.haskell.org/ghcup/msys2/msys2-base-x86_64-20221216.sfx.exe'
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException

The installation process is getting much further using the alternative set-up command for Windows from site https://www.haskell.org/ghcup/guide/#troubleshooting. However too bad, it finally opens a second box displaying error:

--2023-11-12 12:06:09--  https://www.haskell.org/ghcup/sh/bootstrap-haskell
Loaded CA certificate '/usr/ssl/certs/ca-bundle.crt'
Resolving www.haskell.org (www.haskell.org)... 2604:1380:4641:a100::1, 147.75.54.133
Connecting to www.haskell.org (www.haskell.org)|2604:1380:4641:a100::1|:443... connected.
ERROR: The certificate of ‘www.haskell.org’ is not trusted.
ERROR: The certificate of ‘www.haskell.org’ doesn't have a known issuer.

**Comment by hasufell** [comment]
Is this a managed windows installation?

I've heard of certificate issues before on windows, but I'm really not sure what the issue is. haskell.org should have a valid certificate: https://www.ssllabs.com/ssltest/analyze.html?d=haskell.org

**Comment by RMartinF** [comment]
I'm not sure what you mean by "managed". I just copied/pasted the commands from the original and the troubleshooting pages into a Windows PowerShell box and entered manually what the interactive install script asks for. Long ago Windows 10 was installed interactively from DVD and updated to version 11 through the usual online update.

I assume that the troubleshooting script does not turn off certificate checking for all parts that it downloads. Thus the beginning of the troubleshooting script works, but at the end it still encounters a certificate error. Can you turn off checking all downloaded parts?

**Comment by hasufell** [comment]
> Can you turn off checking all downloaded parts?

Yeah, it's possible. That's a bit finicky though to do through the bootstrap scripts.

You can try to do fully manual installation instead (for debug purposes): https://www.haskell.org/ghcup/install/#windows_1

Under step 4 instead of opening a powershell, you would open an msys2 shell (`C:\msys64\msys2_shell.cmd`) and then execute the commands there after setting the environment variable `export GHCUP_CURL_OPTS="--insecure"` (also documented [here](https://www.haskell.org/ghcup/guide/#env-variables)).

I think that should work.

**Comment by RMartinF** [comment]
OK, thank you! I'll try a manual installation. I have but little practice in such things, hopefully I will manage it.
