### ISSUE TITLE
ghcup distributed cabal executable segfaults on aarch64.

### ISSUE THREAD

**Issue by AndreasPK** [haskell/ghcup-hs#930]
This happens sporadically (takes 1-2 hours to trigger typically).

It's likely due to bugs in older version of ghc since it seems cabal has been built with ghc-9.2 which has known memory ordering bugs on aarch64. 

I imagine the simplest thing would be to build cabal with a newer ghc version.

**Comment by hasufell** [comment]
@Kleidukos

**Comment by AndreasPK** [comment]
Cabal built locally with 9.4.7 seems to not have this issue. At least after about 12 hours it hadn't triggered a segfault yet.

**Comment by hasufell** [comment]
> Cabal built locally with 9.4.7 seems to not have this issue. At least after about 12 hours it hadn't triggered a segfault yet.

Did you try with 9.2.8? I'm doing backports for at least 3.6, which I will build with that version.

**Comment by AndreasPK** [comment]
I can give it a try.

**Comment by AndreasPK** [comment]
9.2.8 also didn't crash in ~4-5 hours so likely fine as well.

**Comment by hasufell** [comment]
3.6.2.0-p1 should work now, the next 3.10 release I will also build bindists myself.
