### ISSUE TITLE
Getting changelog from windows TUI crashes the app

### ISSUE THREAD

**Issue by ShrykeWindgrace** [haskell/ghcup-hs#936]
First of al, thanks for bringing TUI to windows, it greatly simplifies tool management!

There's however, a bug I'd like to report:
- run a TUI `ghcup tui`
- press `c` to get a changelog
- observe a crash:
```
ghcup.exe: start: createProcess: does not exist (No such file or directory)
```
My config:
Windows Terminal-1.18, win10, pwsh-7.4.0, ghcup-0.1.20.0.

Cheers!

**Comment by ShrykeWindgrace** [comment]
One of probable causes: `start` is a `pwsh` alias for the `Start-Process` cmdlet, that's not an executable.

In `cmd` I see the same error - probably because `start` is not an executable either, it's a builtin command.

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-hs/pull/937
