### ISSUE TITLE
ghcup intall issue with linux: gmp-devel or equivilant required for linux to fix libgmp.so error

### ISSUE THREAD

**Issue by lineality** [haskell/ghcup-hs#939]
as described here for several linux distros -> https://stackoverflow.com/questions/6360724/installing-ghc-binaries-on-linux-cant-find-libgmp-so

error occurs when trying to use ghcup in linux: "libgmp.so: cannot open shared object file: No such file or directory"

ghcup install extra step required:
$ sudo ___ install gmp-devel
(___ is dnf, apt, etc)

(note: I use fedora and the above fixed the issue)

**Comment by hasufell** [comment]
This is already documented here: https://www.haskell.org/ghcup/install/#system-requirements

And ghcup tells you during installation to install this package. If you ignore the instructions, you get errors.
