### ISSUE TITLE
"recommended" versions out of sync with each other

### ISSUE THREAD

**Issue by Martinsos** [haskell/ghcup-hs#941]
How I usually use GHCup is to set versions of my tools to "recommended" version, and that is what I also recommend to newcomers to Haskell.

I noticed however that the current set of "recommended" versions doesn't gel together -> cabal 3.6.2.0 (recommended) says GHC 9.4.7 (recommended) is too new for it.

I guess the "recommended" tags need some updating? Is there a way to ensure these stay in sync in the future?

I understand this project is actively looking for maintainers so I am thankful for any response here, and let me know if I can help somehow -> I first of all wanted to create this issue to inform of the issue so it can be addressed.

**Comment by hasufell** [comment]
3.6.2.0 being recommended is no mistake. 3.10 is broken on windows.

The cabal/ghc warnings can be ignored.

**Comment by Martinsos** [comment]
Ah ok, wasn't aware of that! I got scared by that warning. Thanks, closing the issue!
