### ISSUE TITLE
GHCup old-style command: unclear suggestion on trying to instal `cabal`

### ISSUE THREAD

**Issue by ffaf1** [haskell/ghcup-hs#957]
See haskell/cabal#9566.

`ghcup install --set cabal latest` outputs a warning about GHC, could be confusing to newcomers.

```
~ % ghcup install --set cabal latest   
[ Warn  ] This is an old-style command for installing GHC. Use 'ghcup install ghc' instead.
```

expected: a similar warning message, but regarding `cabal` instead of GHC.

**Comment by runeksvendsen** [comment]
Looks like the command `install --set cabal latest` is parsed as:

```haskell
Install (Right (InstallOptions {instVer = Just (GHCVersion (GHCTargetVersion {_tvTarget = Nothing, _tvVersion = Version {_vEpoch = Nothing, _vChunks = Chunks (Alphanum "cabal" :| []), _vRel = Nothing, _vMeta = Nothing}})), instBindist = Nothing, instSet = True, isolateDir = Nothing, forceInstall = False, addConfArgs = ["latest"]}))
```

In other words, an old-style `install` command (GHC-only) with the GHC version/tag being `"cabal"` and the CONFIGURE_ARGS being `["latest"]`.

**Comment by runeksvendsen** [comment]
So the confusion here is that the command looks like one that installs the latest version of cabal, but really it's a command that attempts to install a non-existing GHC version with broken configure args.

One solution could be having GHCup print out a human description of the parsed command as the first thing. So the output instead would become:

```
~ % ghcup install --set cabal latest   
[ Info  ] Installing GHC with version tag "cabal" and configure arguments ["latest"]...
[ Warn  ] This is an old-style command for installing GHC. Use 'ghcup install ghc' instead.
...
< some error happens because the "cabal" GHC version doesn't exist >
```

**Comment by hasufell** [comment]
GHCup is already fairly verbose about what it does. I don't believe the user showed the full GHCup output here.

**Comment by runeksvendsen** [comment]
For reference, here's the full output I get on current master (df192ee18e64b6d080adc14f498d97853274a543):

```
$ cabal run exe:ghcup -- install --set cabal latest
[ Warn  ] This is an old-style command for installing GHC. Use 'ghcup install ghc' instead.
[ Warn  ] New ghc version available. If you want to install this latest version, run 'ghcup install ghc 9.8.1'
[ Warn  ] New cabal version available. If you want to install this latest version, run 'ghcup install cabal 3.10.2.0'
[ Warn  ] New hls version available. If you want to install this latest version, run 'ghcup install hls 2.5.0.0'
[ Warn  ] New stack version available. If you want to install this latest version, run 'ghcup install stack 2.13.1'
[ Error ] [GHCup-07140] Both installation and setting the tool failed.
[ ...   ] Install error was: Unable to find a download for cabal
[ ...   ] Set error was: The version cabal of the tool ghc is not installed.
[ Error ] Also check the logs in /Users/rune/.ghcup/logs
```

I still think my suggestion would make it clearer what's going wrong.

**Comment by runeksvendsen** [comment]
But this error certainly needs to be improved as well https://github.com/haskell/ghcup-hs/blob/master/lib/GHCup/Errors.hs#L228 such that it contains at least the "tool".

**Comment by hasufell** [comment]
Yeah, there's room for improvement.

My approach these days is to try not to increase verbosity, unless absolutely necessary, because experience shows that users barely read any on-screen messages. The longer they are, the less likely they're gonna read them.

So we should avoid adding more lines to the terminal when possible and make existing messages more concise and informative.

**Comment by ffaf1** [comment]
I believe there are many way to skin this cat. The offending line is this

```
[ ...   ] Install error was: Unable to find a download for cabal
```

which could give the impression that ghcup is actually trying to download cabal. A slight rewording (e.g.: “Unable to find a download for GHC version `cabal`”) could go a long way.

**Comment by runeksvendsen** [comment]
Proposed fix: https://github.com/haskell/ghcup-hs/pull/960

Error message after proposed fix:

```
[ ...   ] Install error was: Unable to find a download for GHC version 'cabal' on detected platform x86_64-darwin
```
