### ISSUE TITLE
cygwin64

### ISSUE THREAD

**Issue by xloem** [haskell/ghcup-hs#958]
`Unknown platform: CYGWIN_NT-10.0-19045`

I'm just on this system briefly at a library, but I'm surprised I didn't find it mentioned anywhere that cygwin64 is not supported.  Now, it is mentioned !

**Comment by hasufell** [comment]
This is an error from the bootstrap script, not from ghcup itself:

https://github.com/haskell/ghcup-hs/blob/df192ee18e64b6d080adc14f498d97853274a543/scripts/bootstrap/bootstrap-haskell#L316-L326

We could certainly whitelist CYGWIN here too and see how that goes. I don't think making GHC and cabal work with it properly is going to be trivial though.

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-hs/pull/959
