### ISSUE TITLE
Default to `ld.bfd` for bindist configure (alpine or all linux?)

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#967]
GHC likes to pick `ld.gold`. However, experience shows that it's more buggy and unreliable, e.g. https://gitlab.haskell.org/ghc/ghc/-/issues/17508

GHCup strives to give users a configuration that works reliably, not optimize for compilation speed and risk segfaults.

The idea would be to do the following on Alpine or even all Linuxes:

* check if there's a `ld.bfd` binary present
* check if `LD` environment variable is not set
* if both is true, pass `LD=ld.bfd` to the environment executing the bindist configure script

**Comment by bgamari** [comment]
I would recommend not doing this. While `gold` is known to be buggy on some platforms, so is `bfd`. Moreover, while both are buggy, `bfd` is signficantly slower. If anything, my sense is that we should rather favor `lld` instead of `gold.`

**Comment by hasufell** [comment]
> While gold is known to be buggy on some platforms, so is bfd.

In my experience as a past gentoo developer dealing with an attempted effort of supporting ld.gold on one of the biggest linux source distros... I'm fairly confident that `ld.bfd` is less buggy.
