### ISSUE TITLE
Reflect on what went wrong when recommending GHC 9.4

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#969]
GHC 9.4.x was recommended prematurely. There are a couple of things that went wrong:

* an issue with language-c and subsequently with c2hs and all tools depending on it causing build failures on windows across the board: https://github.com/visq/language-c/pull/96
* cabal-3.6 being incompatible with it: https://github.com/haskell/ghcup-hs/issues/966
* https://github.com/haskell/ghcup-hs/issues/962

These caused a significant drop in quality of user experience on windows. There are even some stackoverflow questions regarding the second issue. This went under our radar.

----

Questions to answer:

* why did these issues occur upstream?
* why did we not catch them on our side?
* how do we improve the quality of the 'recommended' tag?

**Comment by runeksvendsen** [comment]
> GHC 9.4.x was recommended prematurely. There are a couple of things that went wrong:
> 
> 1. an issue with language-c and subsequently with c2hs and all tools depending on it causing build failures on windows across the board: [Add support for __builtin_bit_cast visq/language-c#96](https://github.com/visq/language-c/pull/96)
> 2. cabal-3.6 being incompatible with it: [GHCup selected combination of cabal / GHC versions does not work on windows #966](https://github.com/haskell/ghcup-hs/issues/966)
> 3. [ghcup binary built on i386/alpine-3.16 with GHC-9.4.8 segfaults (statically linked) #962](https://github.com/haskell/ghcup-hs/issues/962)

Seems to me like (2) and (3) would be the easiest to catch in CI:

2. Install the default versions of GHC and cabal using GHCup and fail if `cabal build` (on a trivial project) outputs any warnings
3. Also run the ghcup binary produced by the "Build linux binary" action

(1) is harder to catch, since it happens only when building a subset of packages on Hackage — and we can't know beforehand which subset is affected, so that means building all of (or a lot of) Hackage.

**Comment by hasufell** [comment]
Wrt 1.: I'm not sure how stackage team has dealt with that or did they just eject all packages depending on c2hs on windows? That seems unlikely. 

@juhp

**Comment by hasufell** [comment]
I guess you walked into the trap as well 😅

**Comment by juhp** [comment]
Though no Windows users complained to us (Stackage), as far as I know, before or after lts-21 was released

**Comment by hasufell** [comment]
> Though no Windows users complained to us (Stackage), as far as I know, before or after lts-21 was released

Well, given https://github.com/haskell/c2hs/issues/291 I'd be surprised if anything on lts-21 that depends on c2hs builds.

**Comment by hasufell** [comment]
I guess we can exercise a little more self-pity while I close this ticket...
