### ISSUE TITLE
Read-only ghcup usage

### ISSUE THREAD

**Issue by dixonary** [haskell/ghcup-hs#970]
When using `ghcup`, many operations try to modify the installation. This causes issues when, for example, a single `ghcup` installation is needed to be shared across multiple users.

The primary issue I am facing with this (others may have different ones) is that logs seem to be placed inside `.ghcup` in the standard mode. This is fine in principle, as I could just make a symlink out to some benign place - but `ghcup` fails hard if the `logs` subfolder can't be manipulated at will by the program.

Some way of using `ghcup` without it touching any of its own files, maybe some kind of `--read-only` flag which silently throws away any errors on trying to edit files in the base directory, would be a solution - it's possible that people more involved with the project have thoughts about a more elegant approach.

**Comment by hasufell** [comment]
> A single ghcup installation is needed to be shared across multiple users

I'm not sure I follow. What exactly is your configuration? Multiple users have shared write access to the same location?

**Comment by dixonary** [comment]
Multiple users have read access to the same installation of ghcup, which includes ghc, stack, cabal, and so on. None of them have write access.

**Comment by hasufell** [comment]
So what operations do you expect to work when the ghcup base folder is not writable? `ghcup install ghc` obviously can't succeed. So what are the expected semantics?

**Comment by dixonary** [comment]
`ghcup list`, `ghcup whereis`, `ghcup run`, should all work. I think these are the only ones required for `HLS` to interface with ghcup successfully.

**Comment by hasufell** [comment]
HLS does not interface with ghcup. You probably mean [vscode-haskell](https://github.com/haskell/vscode-haskell).

The extension runs a plethora of commands, many of which need write access. E.g.

* `ghcup upgrade`
* `ghcup run ... --install`, which installs toolchain too
* and even `ghcup list` needs write access to `~/.ghcup/cache` unless you passed `ghcup --offline list`

My suggestion is to **disable** the ghcup magic as described here: https://github.com/haskell/vscode-haskell?tab=readme-ov-file#downloaded-binaries

Set the vscode-haskell extension setting `haskell.manageHLS` to `PATH` and then pre-install all the GHC/cabal/stack/HLS versions you expect the students to use via ghcup. Then make sure vscode [knows about the ghcup path](https://github.com/haskell/vscode-haskell?tab=readme-ov-file#stackcabalghc-can-not-be-found).

**Comment by dixonary** [comment]
Thank you for your thoughts. I will try hard-wiring the specific versions of tools and convincing vscode-haskell to use them, as suggested.

**Comment by hasufell** [comment]
There are a couple of things to keep in mind... while you can have many GHC versions installed side by side, you only will have one unqualified GHC in your path (`ghc` instead of `ghc-x.y.x`). So if the students need to use a specific version, they either have to use `with-compiler: ghc-x.y.x` in `cabal.project` or you have to run `ghcup set ghc x.y.z` beforehand.

The second thing is: the official HLS binaries don't support all GHC versions. You can check for example here: https://haskell-language-server.readthedocs.io/en/latest/support/ghc-version-support.html

Or the more precise place: https://github.com/haskell/ghcup-metadata/blob/develop/hls-metadata-0.0.1.json

So HLS 2.5.0.0 currently only supports GHC 9.2.8, 9.4.8, 9.6.3 and 9.8.1.

**Comment by dixonary** [comment]
Yes, having had a quick look through our transitive dependencies earlier, I think we'll be able to safely standardise on GHC 9.4.8 with latest HLS and latest stack. That should make things quite a bit simpler.

**Comment by hasufell** [comment]
What is your stack configuration? You're aware stack will install its own copy of GHC into `~/.stack` if you keep the default configuration? Did you follow https://www.haskell.org/ghcup/guide/#strategy-1-stack-hooks-new-recommended

If you let stack install its own copy of GHC, there's a small chance it will be incompatible with the pre-built HLS binaries.

**Comment by dixonary** [comment]
`system-ghc` and `skip-ghc-check` are both set, which means that *in theory* stack should use the system installation rather than trying to install a fresh one. In practice though, it's still trying to install it.

**Comment by hasufell** [comment]
I'd suggest to try the hooks.

```hs
mkdir -p ~/.stack/hooks/
cat <<EOF > ~/.stack/hooks/ghc-install.sh
#!/bin/sh
set -eu

case $HOOK_GHC_TYPE in
    bindist)
		ghc_path=$(ghcup whereis ghc "$HOOK_GHC_VERSION") || { >&2 echo "Couldn't find $HOOK_GHC_VERSION via ghcup" exit 3 ;}
        printf "%s" "${ghc_path}"
        ;;
    git)
        >&2 echo "Hook doesn't support installing from source"
        exit 1
        ;;
    *)
        >&2 echo "Unsupported GHC installation type: $HOOK_GHC_TYPE"
        exit 2
        ;;
esac
EOF
chmod +x ~/.stack/hooks/ghc-install.sh
```

Then set `system-ghc: false` and `install-ghc: false` in stack config.

**Comment by hasufell** [comment]
oh... make sure the variables are escaped properly in the cat/EOF command.
