### ISSUE TITLE
CI failure on master for "Build binary" on macOS arm64: "configure: error: C compiler cannot create executables"

### ISSUE THREAD

**Issue by runeksvendsen** [haskell/ghcup-hs#971]
Relevant run on master (55030d83da6d59196df28c0eb115cdf19ff20393): https://github.com/haskell/ghcup-hs/actions/runs/7377735561/job/20072046674

**Comment by hasufell** [comment]
That's fixed here: https://github.com/haskell/ghcup-hs/pull/946/files#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaR192

But since https://github.com/haskell/ghcup-hs/issues/962 I haven't been able to finish it

**Comment by runeksvendsen** [comment]
> That's fixed here: https://github.com/haskell/ghcup-hs/pull/946/files#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaR192

Is it possible to separate out that fix from that PR? Or does it depend on the other changes in the PR?
