### ISSUE TITLE
Custom bindists get labeled as "stray" 

### ISSUE THREAD

**Issue by Ei30metry** [haskell/ghcup-hs#974]
I have installed 2 custom bindists, and I was very confused to see how they were labeled as "stray" and went to the bottom of the menu:

![Screenshot 2024-01-11 at 12 39 58 in the afternoon](https://github.com/haskell/ghcup-hs/assets/95337891/994a1d35-041d-453e-b565-a5d3764b5a8a)

Changing the label to "custom" would be more straight forward. 

version: 0.1.20.0

**Comment by hasufell** [comment]
`stray` just means it couldn't be found in any metadata. Since you can switch and edit metadata, I think 'custom' is actually misleading. It can still be a perfectly valid upstream bindist.

**Comment by Ei30metry** [comment]
Okay then. I might be acting too nitpicky!
