### ISSUE TITLE
GHC-9.6 support

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#979]
* https://github.com/haskus/packages/issues/51
* https://github.com/haskell-CI/haskell-ci/issues/698

There are also issues with Cabal version bounds.

**Comment by hasufell** [comment]
https://github.com/jtdaugherty/vty/issues/271

**Comment by runeksvendsen** [comment]
> [jtdaugherty/vty#271](https://github.com/jtdaugherty/vty/issues/271)

So GHC 9.6 is also affected?

**Comment by hasufell** [comment]
New issue: we need to support transformer-0.6, which causes issues with streamly: https://github.com/composewell/streamly/pull/2415

**Comment by hseg** [comment]
Successfully built with passing testsuite using the branch `ghc-9.6` (currently at 4513c39d90b05f7f1a8f208d486df84ca3b408f4) with a bog-standard `stack build && stack test`. Forced `ghc-9.6.5` to get access to the LD patch from #1033.

I also updated to `lts-22.19` (which necessitated adding `ghcup`, `semigroupoids`, `unix-bytestring`, and `cabal-install-parsers` to `allow-newer-deps`) and disabled `build.test-arguments.no-run-tests` to make sure I could run tests. Lockfile is attached.
[stack.yaml.lock](https://github.com/haskell/ghcup-hs/files/15188462/stack.yaml.lock.txt)

**Comment by hseg** [comment]
Arch Linux
