### ISSUE TITLE
Crash with non-standard ghc versions installed

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#983]
Reproduce:

```hs
ghcup install ghc -u "https://gitlab.haskell.org/api/v4/projects/933/jobs/1746054/artifacts/ghc-x86_64-linux-fedora33-release.tar.xz" clc237
ghcup install ghc --force 8.10.7
[ Info  ] Removing the currently installed GHC version first!
[ Info  ] Removing ghc-x.y.z symlinks
[ Info  ] Removing/rewiring ghc-x.y symlinks
[ Info  ] Removing files safely from: /home/hasufell/.ghcup/ghc/8.10.7
ghcup: NonEmpty.fromList: empty list
CallStack (from HasCallStack):
  error, called at libraries/base/Data/List/NonEmpty.hs:200:15 in base:Data.List.NonEmpty
  fromList, called at ./Data/Versions.hs:907:30 in versions-6.0.4-4f1eb2a90b630d9ffb6129d75b6e171ea224af614d5012c00c2210b3e851a0c7:Data.Versions
```

This affects master and the released 0.1.20.0.

**Comment by runeksvendsen** [comment]
@hasufell what's the error that the user sees with the changes in https://github.com/haskell/ghcup-hs/commit/935cb5541be04f92add3fd55a845647381e802df? I assume there's still an error, since parsing fails, but that we just avoid the crash.

**Comment by hasufell** [comment]
> @hasufell what's the error that the user sees with the changes in [935cb55](https://github.com/haskell/ghcup-hs/commit/935cb5541be04f92add3fd55a845647381e802df)? I assume there's still an error, since parsing fails, but that we just avoid the crash.

No, there's no error. Parsing failure is handled correctly.
